/**
 * CLI manifest — single source of truth for every `ant` verb.
 *
 * The Fresh-ANT manual rule says every customer-facing promise has a visible
 * CLI path. Discovery docs, deck CLI companion slides, and
 * `ant docs generate --from-cli` all read from this module so the three
 * surfaces stay in agreement.
 *
 * Each verb declares: usage signature, plain summary, flag list, one
 * canonical example, a grep-able source_ref, and a status.
 *
 * Status meanings:
 *   - 'available'     implemented today; grep source_ref to verify.
 *   - 'needs-wrapper' capability exists server-side, CLI shape sketched in
 *                     DELIVERY-PLAN.md but no wrapper module yet.
 *   - 'planned'       named in DELIVERY-PLAN.md or the fresh-ANT manual,
 *                     CLI wrapper not yet shipped. Provenance is recorded
 *                     in source_ref (DP path vs MANUAL path).
 */

export type CliVerbStatus = 'available' | 'needs-wrapper' | 'planned';

export type CliFlag = {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'enum';
  default?: string;
  constraint?: string;
  summary: string;
};

export type CliVerbRepo = 'fresh-ant' | 'v3' | 'delivery-plan';

export type CliManifestVerb = {
  id: string;
  primaryVerb: string;
  secondaryVerb?: string;
  usage: string;
  summary: string;
  flags: CliFlag[];
  canonical_example: string;
  source_ref: string;
  /** Which repo source_ref resolves against. fresh-ant → /CascadeProjects/ant, v3 → /CascadeProjects/a-nice-terminal, delivery-plan → ANT-Open-Slide spec. Optional; defaults to 'fresh-ant'. */
  repo?: CliVerbRepo;
  status: CliVerbStatus;
  since_version?: string;
};

const ROOMS = 'scripts/ant-cli.mjs';
const PLAN = 'scripts/ant-cli-plan.mjs';
const PLAN_READ = 'scripts/ant-cli-plan-read.mjs';
const CHAT = 'scripts/ant-cli-chat.mjs';
const INV = 'scripts/ant-cli-invites.mjs';
const REG = 'scripts/ant-cli-register.mjs';
const MCP = 'scripts/ant-cli-mcp.mjs';
const DP = 'ANT-Open-Slide/fresh-ant-rules-manual-2026-05-13/DELIVERY-PLAN.md';
const MANUAL = 'ANT-Open-Slide/fresh-ant-rules-manual-2026-05-13/fresh-ant-rules-manual-2026-05-13.html';

const ROOM_ID_EX = 'bvya907eub7tr0lyup0aro';
const PLAN_ID_EX = 'fresh-ant-cli-delivery-2026-05-13';

function f(name: string, type: CliFlag['type'], summary: string, extra: Partial<CliFlag> = {}): CliFlag {
  return { name, type, summary, ...extra };
}

function av(id: string, primary: string, secondary: string | undefined, usage: string, summary: string, flags: CliFlag[], example: string, ref: string): CliManifestVerb {
  return { id, primaryVerb: primary, secondaryVerb: secondary, usage, summary, flags, canonical_example: example, source_ref: ref, status: 'available' };
}

function pl(id: string, primary: string, secondary: string | undefined, usage: string, summary: string, ref: string): CliManifestVerb {
  return { id, primaryVerb: primary, secondaryVerb: secondary, usage, summary, flags: [], canonical_example: `ant ${usage} # planned — design open`, source_ref: ref, repo: 'delivery-plan', status: 'planned' };
}

function nw(id: string, primary: string, secondary: string | undefined, usage: string, summary: string, flags: CliFlag[], example: string, ref: string): CliManifestVerb {
  return { id, primaryVerb: primary, secondaryVerb: secondary, usage, summary, flags, canonical_example: example, source_ref: ref, status: 'needs-wrapper' };
}

export const manifestData: CliManifestVerb[] = [
  // rooms (available)
  av('rooms-list', 'rooms', 'list', 'rooms list', 'List every chat room.', [], 'ant rooms list', `${ROOMS}:96-104`),
  av('rooms-create', 'rooms', 'create', 'rooms create <name...>', 'Create a new chat room.', [], 'ant rooms create antDevTeam', `${ROOMS}:106-118`),
  av('rooms-members', 'rooms', 'members', 'rooms members <roomId>', 'List the members of a room.', [], `ant rooms members ${ROOM_ID_EX}`, `${ROOMS}:120-129`),
  av('rooms-invite', 'rooms', 'invite', 'rooms invite <roomId> <agentHandle>', 'Invite an agent or human into a room (single-step add).', [], `ant rooms invite ${ROOM_ID_EX} @researchant`, `${ROOMS}:131-143`),
  av('rooms-post', 'rooms', 'post', 'rooms post <roomId> <message...>', 'Post a message into a room as the caller (PID-chain resolved).', [], `ant rooms post ${ROOM_ID_EX} 'slice-ready: manifest landed'`, `${ROOMS}:145-156`),
  av('rooms-break', 'rooms', 'break', 'rooms break <roomId> [reason...]', 'Post a context break into a room (system-break message).', [], `ant rooms break ${ROOM_ID_EX} 'phase 1 closed'`, `${ROOMS}:158-173`),
  av('rooms-messages', 'rooms', 'messages', 'rooms messages <roomId>', 'List every message in a room.', [], `ant rooms messages ${ROOM_ID_EX}`, `${ROOMS}:175-185`),

  // chat (available)
  av('chat-tail', 'chat', 'tail',
    'chat tail --room ROOM_ID [--since-order N] [--poll-ms 2000] [--once]',
    'Stream new messages from a room (polls until SIGINT or --once).',
    [
      f('room', 'string', 'Room ID to tail (required).'),
      f('since-order', 'number', 'Skip messages at or below this postOrder.'),
      f('poll-ms', 'number', 'Poll cadence in ms.', { default: '2000', constraint: '500-30000' }),
      f('once', 'boolean', 'Fetch once and exit instead of polling.')
    ],
    `ant chat tail --room ${ROOM_ID_EX} --poll-ms 2000`, `${CHAT}:25-148`),

  // plan write verbs (available)
  av('plan-section', 'plan', 'section',
    'plan section <planId> --title TEXT [--body TEXT] [--order N] [--parent ID]',
    'Append a plan_section event to a plan.',
    [f('title', 'string', 'Section title (required).'), f('body', 'string', 'Optional prose body.'), f('order', 'number', 'Render order hint.', { default: '0' }), f('parent', 'string', 'Parent event id for nesting.')],
    `ant plan section ${PLAN_ID_EX} --title 'Phase 1'`, `${PLAN}:155-164`),
  av('plan-decision', 'plan', 'decision',
    'plan decision <planId> --parent PARENT_ID --title TEXT [--body TEXT]',
    'Append a plan_decision event under a parent.',
    [f('parent', 'string', 'Parent event id (required).'), f('title', 'string', 'Decision title (required).'), f('body', 'string', 'Optional reasoning body.')],
    `ant plan decision ${PLAN_ID_EX} --parent sec-1 --title 'Use TypeScript manifest'`, `${PLAN}:166-176`),
  av('plan-milestone', 'plan', 'milestone',
    'plan milestone <planId> --id ID --title TEXT [--owner @x] [--status S] [--body TEXT]',
    'Append a plan_milestone event.',
    [f('id', 'string', 'Milestone identity key (required).'), f('title', 'string', 'Milestone title (required).'), f('owner', 'string', 'Owner handle (e.g. @researchant).'), f('status', 'string', 'Initial status (e.g. ACTIVE).'), f('body', 'string', 'Optional body.')],
    `ant plan milestone ${PLAN_ID_EX} --id M1.1 --title 'CLI manifest' --owner @researchant --status ACTIVE`, `${PLAN}:192-195`),
  av('plan-milestone-status', 'plan', 'milestone-status',
    'plan milestone-status <planId> --id ID --status S',
    'Flip a milestone status (re-emits plan_milestone with new status).',
    [f('id', 'string', 'Milestone id (required).'), f('status', 'string', 'New status (required).')],
    `ant plan milestone-status ${PLAN_ID_EX} --id M1.1 --status SHIPPED`, `${PLAN}:197-200`),
  av('plan-milestone-archive', 'plan', 'milestone-archive',
    'plan milestone-archive <planId> --id ID',
    'Archive a milestone (status=archived).',
    [f('id', 'string', 'Milestone id (required).')],
    `ant plan milestone-archive ${PLAN_ID_EX} --id M0.legacy`, `${PLAN}:202-204`),
  av('plan-acceptance', 'plan', 'acceptance',
    'plan acceptance <planId> --milestone ID --id ACCEPTANCE_ID --title TEXT',
    'Append a plan_acceptance event under a milestone.',
    [f('milestone', 'string', 'Owning milestone id (required).'), f('id', 'string', 'Acceptance identity key (required).'), f('title', 'string', 'Acceptance title (required).')],
    `ant plan acceptance ${PLAN_ID_EX} --milestone M1.1 --id A1 --title 'schema test passes'`, `${PLAN}:206-218`),
  av('plan-test', 'plan', 'test',
    'plan test <planId> --milestone ID --title TEXT [--status S]',
    'Append a plan_test event under a milestone.',
    [f('milestone', 'string', 'Owning milestone id (required).'), f('title', 'string', 'Test title (required).'), f('status', 'string', 'Initial test status.')],
    `ant plan test ${PLAN_ID_EX} --milestone M1.1 --title 'schema integrity'`, `${PLAN}:232-234`),
  av('plan-test-status', 'plan', 'test-status',
    'plan test-status <planId> --milestone ID --title TEXT --status S',
    'Flip a plan_test status.',
    [f('milestone', 'string', 'Owning milestone id (required).'), f('title', 'string', 'Test title (required).'), f('status', 'string', 'New status (required).')],
    `ant plan test-status ${PLAN_ID_EX} --milestone M1.1 --title 'schema integrity' --status PASS`, `${PLAN}:236-239`),
  av('plan-test-archive', 'plan', 'test-archive',
    'plan test-archive <planId> --milestone ID --title TEXT',
    'Archive a plan_test.',
    [f('milestone', 'string', 'Owning milestone id (required).'), f('title', 'string', 'Test title (required).')],
    `ant plan test-archive ${PLAN_ID_EX} --milestone M1.1 --title 'old test'`, `${PLAN}:241-243`),
  av('plan-decision-archive', 'plan', 'decision-archive',
    'plan decision-archive <planId> --parent PARENT_ID --title TEXT',
    'Archive a plan_decision.',
    [f('parent', 'string', 'Parent event id (required).'), f('title', 'string', 'Decision title (required).')],
    `ant plan decision-archive ${PLAN_ID_EX} --parent sec-1 --title 'old decision'`, `${PLAN}:245-255`),
  av('plan-show', 'plan', 'show',
    'plan show <planId> [--include-archived] [--json]',
    'Render a plan as text or JSON.',
    [f('include-archived', 'boolean', 'Show archived events.'), f('json', 'boolean', 'Emit raw JSON.')],
    `ant plan show ${PLAN_ID_EX} --json`, `${PLAN_READ}:12-32`),

  // invite (available)
  av('invite-create', 'invite', 'create',
    'invite create --room R --label L --password P --kinds cli,mcp [--created-by H] [--admin-token T]',
    'Create a room-scoped invite token (admin-bearer).',
    [f('room', 'string', 'Target room id (required).'), f('label', 'string', 'Invite label (required).'), f('password', 'string', 'Password redeemers must present (required, never logged).'), f('kinds', 'string', 'Allowed client kinds (required).', { constraint: 'csv of cli|mcp|web' }), f('created-by', 'string', 'Creator handle for audit.'), f('admin-token', 'string', 'Bearer; falls back to $ANT_ADMIN_TOKEN.')],
    `ant invite create --room ${ROOM_ID_EX} --label 'pair' --password s3cret --kinds cli,mcp`, `${INV}:126-147`),
  av('invite-list', 'invite', 'list',
    'invite list --room R [--admin-token T]',
    'List invites for a room (admin-bearer).',
    [f('room', 'string', 'Target room id (required).'), f('admin-token', 'string', 'Bearer for admin auth.')],
    `ant invite list --room ${ROOM_ID_EX}`, `${INV}:149-165`),
  av('invite-exchange', 'invite', 'exchange',
    'invite exchange --invite-id ID --password P --kind cli [--handle H]',
    'Exchange an invite + password for a tokenSecret (printed once).',
    [f('invite-id', 'string', 'Invite id (required).'), f('password', 'string', 'Password (required, never logged).'), f('kind', 'enum', 'Client kind (required).', { constraint: 'cli|mcp|web' }), f('handle', 'string', 'Optional handle to claim.')],
    'ant invite exchange --invite-id inv-abc --password s3cret --kind cli --handle @researchant', `${INV}:167-186`),
  av('invite-redeem', 'invite', 'redeem',
    'invite redeem --room ROOM_ID --token TOKEN_SECRET',
    'Redeem a tokenSecret to join a room (token never logged).',
    [f('room', 'string', 'Target room id (required).'), f('token', 'string', 'Token secret from exchange (required).')],
    `ant invite redeem --room ${ROOM_ID_EX} --token tok-xyz`, `${INV}:188-202`),

  // register / add / resolve (available)
  av('register', 'register', undefined,
    'register --handle @x --name terminalN [--ttl 12h] [--pane PANE_ID] [--agent-kind K] [--mirror-v3]',
    'Register the calling terminal with fresh-ANT (PID-chain default-on).',
    [f('handle', 'string', 'Caller handle to associate.'), f('name', 'string', 'Terminal name (required).'), f('ttl', 'string', 'Session TTL.', { default: '12h', constraint: 'Ns|Nm|Nh' }), f('pane', 'string', 'tmux/pty pane id.'), f('agent-kind', 'string', 'e.g. claude_code, codex_cli.'), f('mirror-v3', 'boolean', 'Also mirror to v3 :6458 (opt-in).')],
    'ant register --handle @researchant --name researchant-overnight --agent-kind claude_code', `${REG}:24-31,103-138`),
  av('add-session', 'add', 'session',
    'add session --pid PID --name NAME [--ttl 12h] [--pane PANE_ID] [--agent-kind K]',
    'Add a terminal session by explicit PID.',
    [f('pid', 'number', 'Process id of the terminal (required).'), f('name', 'string', 'Terminal name (required).'), f('ttl', 'string', 'Session TTL.', { default: '12h' }), f('pane', 'string', 'tmux/pty pane id.'), f('agent-kind', 'string', 'e.g. claude_code, codex_cli.')],
    'ant add session --pid 12345 --name worker-2 --agent-kind claude_code', `${REG}:33-44,151-174`),
  av('add-membership', 'add', 'membership',
    'add membership --room ROOM_ID --handle @h --name TERMINAL_NAME',
    'Bind a handle to a terminal in a room (UNIQUE per room).',
    [f('room', 'string', 'Target room id (required).'), f('handle', 'string', 'Handle to bind (required).'), f('name', 'string', 'Terminal name to bind to (required).')],
    `ant add membership --room ${ROOM_ID_EX} --handle @researchant --name researchant-overnight`, `${REG}:33-44,176-193`),
  av('resolve', 'resolve', undefined,
    'resolve [--room ROOM_ID]',
    'Resolve the caller via PID-chain (optional room context).',
    [f('room', 'string', 'Room id for membership lookup.')],
    `ant resolve --room ${ROOM_ID_EX}`, `${REG}:46-53,195-208`),

  // plan update — SHIPPED in v3 by @evolveantcodex M2.1 (canonical @codex2 PASS 2026-05-13)
  { id: 'plan-update', primaryVerb: 'plan', secondaryVerb: 'update',
    usage: 'plan update <planId> --milestone ID --status S --session SESSION_ID [--evidence URL] [--note TEXT] [--json]',
    summary: 'Update an existing plan_milestone in v3 with evidence + note. Requires --session before fetch (B1 fix).',
    flags: [f('milestone', 'string', 'Milestone id (required).'), f('status', 'string', 'New status (required).'), f('session', 'string', 'Owning session id (required, prevents cross-room PATCH drift).'), f('evidence', 'string', 'URL or source_url:https://... ref.'), f('note', 'string', 'Free-text note.'), f('json', 'boolean', 'Emit JSON instead of human text.')],
    canonical_example: `ant plan update ${PLAN_ID_EX} --session O393IH1zFgd_nujpQgnof --milestone M1.1 --status SHIPPED --evidence source_url:https://github.com/Jktfe/ant`,
    source_ref: 'cli/commands/plan.ts:160-190,291-298',
    repo: 'v3', status: 'available' },

  // needs-wrapper (DELIVERY-PLAN.md Phase 2)
  // search-scope (M2.2 full) — SHIPPED in v3 by @claude2 across M2.2a (4 scopes) +
  // M2.2b (artefacts scope). All 5 DELIVERY-PLAN-L57-60 scopes available.
  { id: 'search', primaryVerb: 'search', secondaryVerb: undefined,
    usage: 'search <query> [--scope messages,plans,tasks,docs,artefacts] [--limit N] [--json]',
    summary: 'Scoped search across all 5 manual surfaces (messages/plans/tasks/docs/artefacts). Default scope = messages (backwards compatible). Each result row carries a `kind` discriminator; artefacts rows also carry a `sub_kind` (deck/sheet/tunnel/grant) for the fan-out.',
    flags: [
      f('scope', 'string', 'Comma-separated kinds: messages, plans, tasks, docs, artefacts.', { constraint: 'csv' }),
      f('limit', 'number', 'Total result limit; split per-scope (min 5/scope; artefacts further splits per substore).', { default: '20' }),
      f('json', 'boolean', 'Emit raw aggregated results envelope.')
    ],
    canonical_example: "ant search 'CLI manifest' --scope messages,plans,docs,artefacts",
    source_ref: 'cli/commands/search.ts:1-58',
    repo: 'v3', status: 'available' },
  // search-artefacts (M2.2b) — SHIPPED in v3 by @claude2 (canonical @codex2 PASS pending).
  // Closes M2.2 full: fifth scope from DELIVERY-PLAN L57-60. Server-side fans out
  // across the 4 artefact sub-stores (deck/sheet/tunnel/grant); each row carries
  // a `sub_kind` discriminator so the CLI renders deck/sheet/tunnel/grant lines.
  { id: 'search-artefacts', primaryVerb: 'search', secondaryVerb: undefined,
    usage: 'search <query> --scope artefacts [--limit N] [--json]',
    summary: 'Scoped search across artefact stores (deck, sheet, tunnel, grant). Each row has `kind=artefacts` + a `sub_kind` discriminator. Fans out to 4 LIKE-on-title/slug/topic queries server-side; per-sub-store budget = limit/4.',
    flags: [
      f('scope', 'string', 'Use "artefacts" (single or in a CSV with other kinds).'),
      f('limit', 'number', 'Total result limit; split per-substore (min 1 each).', { default: '20' }),
      f('json', 'boolean', 'Emit raw aggregated results envelope.')
    ],
    canonical_example: "ant search 'open-slide' --scope artefacts",
    source_ref: 'cli/commands/search.ts:1-58',
    repo: 'v3', status: 'available' },
  // sessions-digest — SHIPPED in v3 by @claude2 M2.3 (canonical @codex2 PASS 2026-05-14)
  { id: 'sessions-digest', primaryVerb: 'sessions', secondaryVerb: 'digest',
    usage: 'sessions <id> digest [--json]',
    summary: 'Print a session digest (message count, participants, duration, key terms). Wraps GET /api/sessions/:id/digest. Human text by default; --json for envelope.',
    flags: [f('json', 'boolean', 'Emit JSON instead of human text.')],
    canonical_example: 'ant sessions O393IH1zFgd_nujpQgnof digest --json',
    source_ref: 'cli/commands/sessions.ts:31-61',
    repo: 'v3', status: 'available' },

  // planned (DELIVERY-PLAN.md Phase 3+) — placeholders for design
  av('audit-permissions', 'audit', 'permissions', 'audit permissions --room ROOM_ID [--json]', 'List every member of a room with their identity proof: handle, terminal_id, terminal_name, agent_kind, joined_at. Read-only.', [f('room', 'string', 'Room ID (required).'), f('json', 'boolean', 'Emit JSON instead of human text.')], `ant audit permissions --room ${ROOM_ID_EX}`, 'scripts/ant-cli-audit.mjs:12-22,53-75'),
  av('fingerprint-detect', 'fingerprint', 'detect', 'fingerprint detect <terminal-id> [--json] [--write-back] [--admin-token T]', 'Detect agent kind via 5-source cascade (process-tree → tmux-title → capture-fn → name → default). Returns kind/driver/confidence/fallback/evidence. Read-only by default; --write-back opts in to mutate terminals.agent_kind+meta when confidence=HIGH (admin-bearer). NEVER overwrites remote/browser agent_kind. Detector in fingerprintDetector.ts (PsRunner+makeProcessTreeFn walker, cycle/depth-bounded); route in src/routes/api/terminals/[id]/fingerprint/+server.ts; CLI in scripts/ant-cli-fingerprint.mjs.', [f('json', 'boolean', 'Emit JSON instead of human text.'), f('write-back', 'boolean', 'Opt in to write-back when confidence=HIGH (admin-bearer required).'), f('admin-token', 'string', 'Admin bearer (writeBack only). Falls back to ANT_ADMIN_TOKEN env.')], 'ant fingerprint detect term-abc --write-back', 'src/lib/server/fingerprintDetector.ts:1-175,scripts/ant-cli-fingerprint.mjs:1-76,src/routes/api/terminals/[id]/fingerprint/+server.ts:1-25'),
  av('linkedchat-list', 'linkedchat', 'list', 'linkedchat list <terminal-id> [--json]', 'List terminal chat allow/deny rows. Read-only but pidChain-gated to avoid permission-row leaks.', [f('json', 'boolean', 'Emit JSON.')], 'ant linkedchat list term_abc', 'scripts/ant-cli-linkedchat.mjs:15-21,84-92'),
  av('linkedchat-allow', 'linkedchat', 'allow', 'linkedchat allow <terminal-id> --handle @x [--reason "..."] [--json]', 'Allow a terminal chat subject handle for one terminal. Writes are pidChain-gated self-or-room-owner.', [f('handle', 'string', 'Subject handle to allow (required).'), f('reason', 'string', 'Optional audit reason.'), f('json', 'boolean', 'Emit JSON.')], 'ant linkedchat allow term_abc --handle @viewer --reason pairing', 'scripts/ant-cli-linkedchat.mjs:15-21,95-107'),
  av('linkedchat-deny', 'linkedchat', 'deny', 'linkedchat deny <terminal-id> --handle @x [--reason "..."] [--json]', 'Deny a terminal chat subject handle for one terminal; deny is the reversible remove path.', [f('handle', 'string', 'Subject handle to deny (required).'), f('reason', 'string', 'Optional audit reason.'), f('json', 'boolean', 'Emit JSON.')], 'ant linkedchat deny term_abc --handle @viewer', 'scripts/ant-cli-linkedchat.mjs:15-21,95-107'),
  av('status-show-v1', 'status', 'show', 'status show --room ROOM_ID [--json]', 'Show pane/terminal delivery status (verified/stale/unknown) per room member.', [f('room', 'string', 'Room ID (required).'), f('json', 'boolean', 'Emit JSON instead of human text.')], `ant status show --room ${ROOM_ID_EX}`, `scripts/ant-cli-status.mjs:12-22,57-79`),
  av('status-show-v2', 'status', 'show', 'status show --room ROOM_ID --rich [--json]  OR  status show --terminal TERMINAL_ID --rich [--json]', 'Rich agent status (idle/thinking/working/response-required) per FL2. Fingerprint primary, hooks/ANT-activity/PID fallback. GLOBAL per agent. CLI in ant-cli-status.mjs; store agentStatusStore.ts; poller agentStatusPoller.ts; cascade fingerprintHasher.ts; touchpoints terminalsStore.ts + messages route + pty-inject-fanout.', [f('room', 'string', 'Room ID (room-scope rich list).'), f('terminal', 'string', 'Terminal ID (single-terminal rich row).'), f('rich', 'boolean', 'Required for v2 rich response.'), f('json', 'boolean', 'Emit JSON instead of human text.')], `ant status show --terminal term-abc --rich`, 'scripts/ant-cli-status.mjs:14-23,56-76'),
  av('status-install-line', 'status', 'install-line', 'status install-line --cli qwen-cli [--target PATH] [--json]', 'Install the status-line pilot for qwen-cli. Backs up any existing statusline-command.sh and writes a script that preserves Qwen visible status text while emitting ANT-canonical state JSON under ~/.ant/state/qwen-cli/.', [f('cli', 'enum', 'CLI to install for. Pilot supports qwen-cli.', { constraint: 'qwen-cli' }), f('target', 'string', 'Override the target statusline-command.sh path.'), f('json', 'boolean', 'Emit JSON instead of human text.')], 'ant status install-line --cli qwen-cli', 'scripts/ant-cli-status.mjs:27,104-225'),
  av('delivery-verify', 'delivery', 'verify', 'delivery verify --terminal TERMINAL_ID [--json]', 'Show pane/terminal delivery state (verified/stale/unknown) + plain-English reason for one terminal. Read-only.', [f('terminal', 'string', 'Terminal ID (required).'), f('json', 'boolean', 'Emit JSON instead of human text.')], 'ant delivery verify --terminal term-abcdefgh-x', 'scripts/ant-cli-delivery.mjs:12-22,53-65'),
  av('room-mode', 'room', 'mode', 'room mode --room ROOM_ID [--set brainstorm|heads-down|closed] [--toggle] [--json]',
    'Read or set per-room conversation mode (brainstorm/heads-down/closed). --toggle cycles brainstorm↔heads-down (refuses while closed). Write path PUTs through IDENTITY-GATE via pidChain.',
    [f('room', 'string', 'Room ID (required).'),
     f('set', 'enum', 'Set the mode to brainstorm, heads-down, or closed.', { constraint: 'brainstorm|heads-down|closed' }),
     f('toggle', 'boolean', 'Cycle brainstorm↔heads-down (refuses while closed; mutually exclusive with --set).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant room mode --room ${ROOM_ID_EX} --set heads-down`, `scripts/ant-cli-room.mjs:16,120-163`),
  av('room-responders', 'room', 'responders',
    'room responders --room ROOM_ID [--set @h1,@h2,@h3 | --add @h [--at N] | --remove @h | --move @h --to N] [--json]',
    'Read or edit the per-room ordered responder list. In heads-down mode the fanout picks the first responder whose pane_status is verified; if no eligible responder exists, a rate-limited no-responder system marker is emitted. Writes are IDENTITY-GATEd via pidChain.',
    [f('room', 'string', 'Room ID (required).'),
     f('set', 'string', 'Comma-separated handles to REPLACE the responder list.'),
     f('add', 'string', 'Handle to insert into the responder list.'),
     f('at', 'number', 'Position to insert at (used with --add).'),
     f('remove', 'string', 'Handle to remove from the responder list.'),
     f('move', 'string', 'Handle to reorder (used with --to).'),
     f('to', 'number', 'Target position (used with --move).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant room responders --room ${ROOM_ID_EX} --set @claude2,@codex2`,
    `scripts/ant-cli-room.mjs:18,168-225`),
  av('chat-break', 'chat', 'break', 'chat break --room ROOM_ID [--reason TEXT] [--handle @h] [--json]', 'Post a context break with an optional reason.',
    [f('room', 'string', 'Room ID (required).'), f('reason', 'string', 'Optional context-break reason.'), f('handle', 'string', 'Posting handle.', { default: '@cli' }), f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat break --room ${ROOM_ID_EX} --reason 'phase changed'`, `${CHAT}:36,187-197`),
  av('chat-read', 'chat', 'read', 'chat read --room ROOM_ID --message MESSAGE_ID [--handle @h] [--json]', 'Mark a message as read by the caller handle.',
    [f('room', 'string', 'Room ID (required).'), f('message', 'string', 'Message ID (required).'), f('handle', 'string', 'Reader handle.', { default: '@cli' }), f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat read --room ${ROOM_ID_EX} --message msg_123 --handle @researchant`, `${CHAT}:37,199-210`),
  av('chat-typing', 'chat', 'typing', 'chat typing --room ROOM_ID [--handle @h] [--json]', 'Send a typing heartbeat for the caller handle.',
    [f('room', 'string', 'Room ID (required).'), f('handle', 'string', 'Member handle.', { default: '@cli' }), f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat typing --room ${ROOM_ID_EX} --handle @claude2`, `${CHAT}:38,212-220`),
  av('chat-draft', 'chat', 'draft', 'chat draft --room ROOM_ID (--text TEXT | --clear) [--handle @h] [--json]', 'Save or clear a room composer draft for the caller handle.',
    [f('room', 'string', 'Room ID (required).'), f('text', 'string', 'Draft text to save.'), f('clear', 'boolean', 'Clear the saved draft.'), f('handle', 'string', 'Author handle.', { default: '@cli' }), f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat draft --room ${ROOM_ID_EX} --text 'follow up later' --handle @codex`, `${CHAT}:39,222-242`),
  av('discussion-create', 'discussion', 'create', 'discussion create --room ROOM_ID --from MESSAGE_ID [--title "..."] [--json]', 'Spin a named side-thread off a parent message in a room. Identity-gated via pidChain.', [f('room', 'string', 'Room id (required).'), f('from', 'string', 'Parent message id (required).'), f('title', 'string', 'Optional side-thread title.'), f('json', 'boolean', 'Emit JSON.')], `ant discussion create --room ${ROOM_ID_EX} --from msg_p --title 'follow-up'`, `scripts/ant-cli-discussion.mjs:33,79-89`),
  av('discussion-close', 'discussion', 'close', 'discussion close --id DISCUSSION_ID --summary "..." [--json]', 'Close (or re-close) a discussion with a summary. PATCH-on-root per Q5; subsequent calls update summary in place (Q4-4b). Soft-close per Q3-3c — subsequent posts allowed with envelope marker.', [f('id', 'string', 'Discussion id (required).'), f('summary', 'string', 'Non-empty summary (required).'), f('json', 'boolean', 'Emit JSON.')], `ant discussion close --id d_1 --summary 'agreed to defer'`, `scripts/ant-cli-discussion.mjs:91-100`),
  av('room-invite', 'room', 'invite', 'room invite <create|list|exchange|redeem|revoke> [flags]', 'Closed-room invite tokens; thin alias to `ant invite`. revoke (M3.7b) cascades to derived tokens via chatInviteStore.revokeInvite. Admin verbs need ANT_ADMIN_TOKEN.', [f('invite-id', 'string', 'Invite id (for exchange/redeem/revoke).'), f('admin-token', 'string', 'Admin bearer (falls back to $ANT_ADMIN_TOKEN).'), f('room', 'string', 'Room id (for create/list/redeem).'), f('password', 'string', 'Password (never logged).'), f('json', 'boolean', 'Emit JSON.')], `ant room invite revoke --invite-id inv_4991d5b38ad48962`, `scripts/ant-cli-room.mjs:2,15,scripts/ant-cli-invites.mjs:31,207-221`),
  av('room-members', 'room', 'members', 'room members --room ROOM_ID | room add-member/remove-member/aliases/set-alias/clear-alias --room ROOM_ID ...', 'Manage room members and per-room aliases.', [f('room', 'string', 'Room ID (required).'), f('handle', 'string', 'Member handle for mutating verbs.'), f('alias', 'string', 'Room-scoped alias for set-alias.'), f('json', 'boolean', 'Emit JSON instead of human text.')], `ant room members --room ${ROOM_ID_EX}`, `scripts/ant-cli-room.mjs:7-12,61-114`),
  av('reaction', 'reaction', undefined, 'reaction list|add|remove --room ROOM_ID --message MESSAGE_ID [--handle @h --emoji EMOJI] [--json]', 'Manage the canonical reactions on a message.', [f('room', 'string', 'Room ID (required).'), f('message', 'string', 'Message ID (required).'), f('handle', 'string', 'Reactor handle for add/remove.'), f('emoji', 'string', 'Canonical reaction emoji for add/remove.'), f('json', 'boolean', 'Emit JSON instead of human text.')], `ant reaction list --room ${ROOM_ID_EX} --message msg_123`, `scripts/ant-cli-reaction.mjs:7-9,59-90`),
  av('remote-admit', 'remote', 'admit', 'remote admit --room <id> [--lifetime today|48h|7d|indefinite]', 'Mint a remote-invite code (admin-bearer). Returns code + admission_id + 20-min acceptance window.', [f('room', 'string', 'Local room id (required).'), f('lifetime', 'enum', 'Lifetime preset.', { default: '48h', constraint: 'today|48h|7d|indefinite' }), f('admin-token', 'string', 'Admin bearer; falls back to $ANT_ADMIN_TOKEN.')], `ant remote admit --room ${ROOM_ID_EX} --lifetime 48h`, 'scripts/ant-cli-remote.mjs:45-55,83-92'),
  av('remote-redeem', 'remote', 'redeem', 'remote redeem --code <code> --admission-id <id> --remote-url <url> --label <label> [--direction in|out|both]', 'Operator-on-remote-instance redeems a code received out-of-band; receives bridge_token + mapping_id (single-use).', [f('code', 'string', 'Invite code (required).'), f('admission-id', 'string', 'Admission id (required).'), f('remote-url', 'string', 'Local ANT base URL (required).'), f('label', 'string', 'Remote instance label (required).'), f('direction', 'enum', 'Bridge direction.', { default: 'both', constraint: 'in|out|both' })], 'ant remote redeem --code ANT-7K9-WXP4 --admission-id adm_xyz --remote-url https://mac.local:6174 --label inst-a', 'scripts/ant-cli-remote.mjs:45-55,93-105'),
  av('remote-mapping', 'remote', 'mapping', 'remote mapping list --room <id> | show <id> | revoke <id>', 'List/show/revoke active remote bridge mappings. v1 lists active only — --include-revoked is V2.', [f('room', 'string', 'Room id (required for list).'), f('admin-token', 'string', 'Admin bearer.')], `ant remote mapping list --room ${ROOM_ID_EX}`, 'scripts/ant-cli-remote.mjs:45-55,106-134'),
  av('remote-room-send', 'remote-room', 'send', 'remote-room send <mapping-id> --msg <text>', 'Local operator queues an OUT-direction event for the remote bridge (admin-bearer).', [f('msg', 'string', 'Message body (required).'), f('admin-token', 'string', 'Admin bearer.')], "ant remote-room send map_abc --msg 'hello'", 'scripts/ant-cli-remote.mjs:57-68,135-144'),
  av('remote-room-status', 'remote-room', 'status', 'remote-room status <mapping-id>', 'V2 (M4 v2 count surface, 2026-05-14): wraps GET /api/remote-ant/mappings/:id/status — mapping detail (id + label + last_seen + direction) PLUS delivery_state counts (accepted + quarantined + delivered + pending + failed). CLI falls back to v1 /mappings/:id mapping-detail-only when /status unavailable.', [f('admin-token', 'string', 'Admin bearer.')], 'ant remote-room status map_abc', 'scripts/ant-cli-remote.mjs:57-68,145-164'),
  av('remote-room-ack', 'remote-room', 'ack', 'remote-room ack <event-id>', 'Operator clears a quarantined event after manual review (admin-bearer).', [f('admin-token', 'string', 'Admin bearer.')], 'ant remote-room ack evt_abc', 'scripts/ant-cli-remote.mjs:57-68,156-164'),
  av('remote-room-quarantine', 'remote-room', 'quarantine', 'remote-room quarantine list [--mapping-id <id>]', 'List quarantined remote events newest-first. Filter by mapping when --mapping-id set.', [f('mapping-id', 'string', 'Filter by mapping id.'), f('admin-token', 'string', 'Admin bearer.')], 'ant remote-room quarantine list', 'scripts/ant-cli-remote.mjs:57-68,165-176'),
  av('mcp', 'mcp', undefined, 'mcp list|grant|revoke --room ROOM_ID|--token-id TOKEN_ID [--admin-token T] [--json]', 'Manage MCP adapter lifecycle. Grant prints tokenSecret once; list/revoke never print token bytes.', [f('room', 'string', 'Room id for list/grant.'), f('handle', 'string', 'MCP handle for grant.'), f('label', 'string', 'Optional client label.'), f('token-id', 'string', 'Token id for revoke.'), f('include-revoked', 'boolean', 'Include revoked grants in list.'), f('admin-token', 'string', 'Admin bearer; falls back to $ANT_ADMIN_TOKEN.'), f('json', 'boolean', 'Emit JSON.')], `ant mcp grant --room ${ROOM_ID_EX} --handle @mcp --label 'Claude Desktop'`, `${MCP}:14-24,81-122;src/routes/api/mcp/grants/+server.ts:1-57;src/routes/api/mcp/grants/[tokenId]/revoke/+server.ts:1-22;src/lib/server/mcpGrantStore.ts:59-111`),
  // M4.4 chair handoff — SHIPPED in fresh-ANT by @claude2 (canonical @codex2 PASS).
  // 4 explicit subverbs replace the single placeholder row per Q5 lock; each entry
  // points at the CLI handler line range + the relevant route file.
  av('chair-enable', 'chair', 'enable', 'chair enable',
    'Enable the per-instance Chair plug-in. Writes are pidChain-gated.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant chair enable',
    'scripts/ant-cli-chair.mjs:59-66;src/routes/api/chair-enabled/+server.ts:1-54'),
  av('chair-disable', 'chair', 'disable', 'chair disable',
    'Disable the per-instance Chair plug-in (chair UI hides; data API still readable).',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant chair disable',
    'scripts/ant-cli-chair.mjs:68-75;src/routes/api/chair-enabled/+server.ts:1-54'),
  av('chair-handoff', 'chair', 'handoff', 'chair handoff <room-id> --to @handle',
    'Re-assign the chair role for a room to another room member. Caller must be a member; target must be a member; idempotent on same-chair.',
    [f('to', 'string', 'Target handle (required).'), f('json', 'boolean', 'Emit JSON.')],
    `ant chair handoff ${ROOM_ID_EX} --to @codex`,
    'scripts/ant-cli-chair.mjs:77-88;src/routes/api/chat-rooms/[roomId]/chair/handoff/+server.ts:1-59'),
  av('chair-board', 'chair', 'board', 'chair board <room-id> [--json]',
    'Print the per-room chair digest (message count, attention state, key terms). Wraps GET /api/chair + client-filters by roomId.',
    [f('json', 'boolean', 'Emit JSON.')],
    `ant chair board ${ROOM_ID_EX}`,
    'scripts/ant-cli-chair.mjs:90-109;src/routes/api/chair/+server.ts:1-16'),
  // M4.5 interview start/end — SHIPPED in fresh-ANT by @claude2 (canonical @codex2 PASS T2).
  av('interview-start', 'interview', 'start', 'interview start --room <id> --with @handle [--json]',
    'Start a focused interview between caller (interviewer) and a target room member. One active interview per room max. Both caller and subject must be room members. Writes are pidChain-gated.',
    [f('room', 'string', 'Room ID (required).'), f('with', 'string', 'Subject handle (required).'), f('json', 'boolean', 'Emit JSON.')],
    `ant interview start --room ${ROOM_ID_EX} --with @kimi`,
    'scripts/ant-cli-interview.mjs:56-68;src/routes/api/chat-rooms/[roomId]/interviews/+server.ts:1-55'),
  av('interview-end', 'interview', 'end', 'interview end <interview-id> [--reason "..."] [--json]',
    'End an active interview by id. Only the interviewer or the subject of THIS interview may end it (ordinary other members 403). Idempotent on already-ended.',
    [f('reason', 'string', 'Optional end-reason audit string.'), f('json', 'boolean', 'Emit JSON.')],
    'ant interview end iv_abc123 --reason "wrap-up"',
    'scripts/ant-cli-interview.mjs:70-80;src/routes/api/interviews/[interviewId]/end/+server.ts:1-43'),
  // M-SHARED-SCREENSHOTS T1 + T2-wiring + T3a — shared screenshot folder per
  // room (opt-in). Delta-2 (JWPK Q-A/Q-E, 2026-05-14) drops storage caps + TTL +
  // vacuum cron; soft-delete via deleted_at_ms; manual prune lands T3b.
  av('screenshot-enable', 'screenshot', 'enable', 'screenshot enable <room-id> [--json]',
    'Enable the shared screenshot folder for a room (opt-in per room, pidChain-gated). Wraps PUT /api/chat-rooms/:roomId/screenshots/enable.',
    [f('json', 'boolean', 'Emit JSON.')],
    `ant screenshot enable ${ROOM_ID_EX}`,
    'scripts/ant-cli-screenshot.mjs:62-70;src/routes/api/chat-rooms/[roomId]/screenshots/enable/+server.ts:1-34'),
  av('screenshot-disable', 'screenshot', 'disable', 'screenshot disable <room-id> [--json]',
    'Disable the shared screenshot folder for a room (rows preserved; future captures rejected).',
    [f('json', 'boolean', 'Emit JSON.')],
    `ant screenshot disable ${ROOM_ID_EX}`,
    'scripts/ant-cli-screenshot.mjs:72-80;src/routes/api/chat-rooms/[roomId]/screenshots/enable/+server.ts:1-34'),
  av('screenshot-list', 'screenshot', 'list', 'screenshot list <room-id> [--json]',
    'List active screenshots in a room newest-first (soft-deleted excluded). Wraps GET /api/chat-rooms/:roomId/screenshots.',
    [f('json', 'boolean', 'Emit JSON.')],
    `ant screenshot list ${ROOM_ID_EX}`,
    'scripts/ant-cli-screenshot.mjs:82-94;src/routes/api/chat-rooms/[roomId]/screenshots/+server.ts:1-19'),
  av('screenshot-take', 'screenshot', 'take', 'screenshot take <room-id> --file PATH [--topic TEXT] [--taken-by @h] [--json]',
    'Capture a PNG file into the shared screenshot folder for a room (dedup-before-write via sha256 + temp-then-rename atomic). Wraps POST /api/chat-rooms/:roomId/screenshots.',
    [f('file', 'string', 'PNG file path (required).'), f('topic', 'string', 'Optional topic label.'), f('taken-by', 'string', 'Caller handle.', { default: '@cli' }), f('json', 'boolean', 'Emit JSON.')],
    `ant screenshot take ${ROOM_ID_EX} --file /tmp/grab.png --topic 'login-bug'`,
    'scripts/ant-cli-screenshot.mjs:14-22,75-95;src/lib/server/screenshotCapture.ts:1-90;src/routes/api/chat-rooms/[roomId]/screenshots/+server.ts:30-80'),
  av('screenshot-prune', 'screenshot', 'prune', 'screenshot prune <room-id> --sha SHA [--json]',
    'Soft-delete a screenshot in a room (file bytes survive on disk per JWPK Q-E). Idempotent — second prune returns changed=false. Wraps POST /api/chat-rooms/:roomId/screenshots/:sha/prune (pidChain-gated).',
    [f('sha', 'string', 'SHA-256 of the screenshot to prune (required).'), f('json', 'boolean', 'Emit JSON.')],
    `ant screenshot prune ${ROOM_ID_EX} --sha 0000000000000000000000000000000000000000000000000000000000000000`,
    'scripts/ant-cli-screenshot.mjs:82-95;src/routes/api/chat-rooms/[roomId]/screenshots/[sha]/prune/+server.ts:1-44'),
  // CLI-HOOK-BRIDGE Phase 1B (2026-05-15, JWPK): wires Claude Code hooks
  // into ANT's /api/cli-hook receiver. Idempotent install/uninstall +
  // status. Defaults to 8 high-signal events (SessionStart/End,
  // UserPromptSubmit, Pre/PostToolUse, Stop, Pre/PostCompact).
  av('hooks-install', 'hooks', 'install', 'hooks install [--events <a,b,c>] [--json]',
    'Wire Claude Code hooks → ANT /api/cli-hook receiver. Idempotent merge into ~/.claude/settings.json (path override via ANT_HOOKS_SETTINGS_PATH env). Preserves user-defined hooks.',
    [f('events', 'string', 'Comma-separated event names. Defaults to the 8 high-signal events.'), f('json', 'boolean', 'Emit JSON.')],
    'ant hooks install',
    'scripts/ant-cli-hooks.mjs:175-205;src/routes/api/cli-hook/+server.ts:1-130'),
  av('hooks-uninstall', 'hooks', 'uninstall', 'hooks uninstall [--json]',
    'Remove only the hooks ANT installed (identified by receiver URL marker). Leaves user-defined hooks untouched.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant hooks uninstall',
    'scripts/ant-cli-hooks.mjs:207-237;src/routes/api/cli-hook/+server.ts:1-130'),
  av('hooks-status', 'hooks', 'status', 'hooks status [--json]',
    'Show which Claude Code hook events are currently wired to the ANT receiver, plus any default events not yet installed.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant hooks status',
    'scripts/ant-cli-hooks.mjs:239-265'),
  av('hooks-doctor', 'hooks', 'doctor', 'hooks doctor [--json]',
    'Pre-launch health check across all 6 CLI hook dirs (~/.{claude,codex,gemini,qwen,pi,copilot}/hooks/). Reports hardcoded URLs (no env override), stale `:6457` v3 default ports, and on-disk template drift vs canonical scripts/ant-hooks-templates/. Exit 0 = clean; 1 = findings; 2 = read errors. Lifts the rubric from docs/audits/hardcoded-ports-2026-05-19.md into a one-command runbook for operators.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant hooks doctor',
    'scripts/ant-cli-hooks.mjs:327-440'),
  av('voice-elevenlabs-test', 'voice', 'elevenlabs',
    'voice elevenlabs test --text "..." [--voice <id>] [--out <path>] [--json]',
    'Smoke-test the optional ElevenLabs TTS plug-in. Reads ELEVENLABS_API_KEY from env; skips gracefully if unset. Writes the returned mp3 to --out (default /tmp/ant-voice-test.mp3).',
    [f('text', 'string', 'Text to synthesise (required).'),
     f('voice', 'string', 'ElevenLabs voice id.', { default: '21m00Tcm4TlvDq8ikWAM' }),
     f('out', 'string', 'Output mp3 path.', { default: '/tmp/ant-voice-test.mp3' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant voice elevenlabs test --text "hello world"',
    'scripts/ant-cli-voice.mjs:24-40,63-134'),
  av('docs-generate', 'docs', 'generate', 'docs generate --from-cli [--out-dir DIR] [--filename NAME]', 'Generate manifest-derived markdown to disk by fetching /discover.md. HTML render lives at /discover.', [f('from-cli', 'boolean', 'Canonical source flag (required).'), f('out-dir', 'string', 'Output directory.', { default: './docs' }), f('filename', 'string', 'Output filename (no path separators, no ..).', { default: 'cli-discovery.md' })], 'ant docs generate --from-cli --out-dir ./docs --filename cli-discovery.md', 'scripts/ant-cli-docs.mjs:26-40,78-101'),
  // Task #124 docs subsystem: room-scoped markdown doc CRUD.
  av('docs-list', 'docs', 'list', 'docs list --room ROOM_ID [--json]', 'List markdown docs in a room.', [f('room', 'string', 'Target room id (required).'), f('json', 'boolean', 'Output JSON instead of table.')], 'ant docs list --room zj4jlety9q', 'scripts/ant-cli-docs.mjs:110-140'),
  av('docs-add', 'docs', 'add', 'docs add --room ROOM_ID --title TITLE [--content TEXT] [--json]', 'Create a markdown doc in a room.', [f('room', 'string', 'Target room id (required).'), f('title', 'string', 'Doc title (required).'), f('content', 'string', 'Markdown content.', { default: '' }), f('json', 'boolean', 'Output JSON instead of summary.')], 'ant docs add --room zj4jlety9q --title "Runbook" --content "# Steps\n1. ..."', 'scripts/ant-cli-docs.mjs:142-180'),
  av('docs-update', 'docs', 'update', 'docs update --room ROOM_ID --id DOC_ID [--title TEXT] [--content TEXT] [--json]', 'Update a markdown doc.', [f('room', 'string', 'Target room id (required).'), f('id', 'string', 'Doc id (required).'), f('title', 'string', 'New title.'), f('content', 'string', 'New markdown content.'), f('json', 'boolean', 'Output JSON.')], 'ant docs update --room zj4jlety9q --id abc --title "Updated"', 'scripts/ant-cli-docs.mjs:167-196'),
  av('docs-remove', 'docs', 'remove', 'docs remove --room ROOM_ID --id DOC_ID [--json]', 'Soft-delete a markdown doc.', [f('room', 'string', 'Target room id (required).'), f('id', 'string', 'Doc id (required).'), f('json', 'boolean', 'Output JSON.')], 'ant docs remove --room zj4jlety9q --id abc', 'scripts/ant-cli-docs.mjs:198-218'),
  // Task #126 decks subsystem: room-scoped slide deck CRUD.
  av('decks-list', 'decks', 'list', 'decks list --room ROOM_ID [--json]', 'List slide decks in a room.', [f('room', 'string', 'Target room id (required).'), f('json', 'boolean', 'Output JSON instead of table.')], 'ant decks list --room zj4jlety9q', 'scripts/ant-cli-decks.mjs:1-50'),
  av('decks-add', 'decks', 'add', 'decks add --room ROOM_ID --title TITLE [--slides-json JSON] [--theme TEXT] [--json]', 'Create a slide deck in a room.', [f('room', 'string', 'Target room id (required).'), f('title', 'string', 'Deck title (required).'), f('slides-json', 'string', 'Slides JSON array.', { default: '[]' }), f('theme', 'string', 'Deck theme.', { default: 'default' }), f('json', 'boolean', 'Output JSON.')], 'ant decks add --room zj4jlety9q --title "Pitch" --slides-json "[{\\"id\\":\\"s1\\",\\"title\\":\\"Intro\\",\\"content\\":\\"Hello\\"}]"', 'scripts/ant-cli-decks.mjs:52-100'),
  av('decks-update', 'decks', 'update', 'decks update --room ROOM_ID --id DECK_ID [--title TEXT] [--slides-json JSON] [--theme TEXT] [--json]', 'Update a slide deck.', [f('room', 'string', 'Target room id (required).'), f('id', 'string', 'Deck id (required).'), f('title', 'string', 'New title.'), f('slides-json', 'string', 'New slides JSON.'), f('theme', 'string', 'New theme.'), f('json', 'boolean', 'Output JSON.')], 'ant decks update --room zj4jlety9q --id abc --title "Updated"', 'scripts/ant-cli-decks.mjs:102-150'),
  av('decks-remove', 'decks', 'remove', 'decks remove --room ROOM_ID --id DECK_ID [--json]', 'Soft-delete a slide deck.', [f('room', 'string', 'Target room id (required).'), f('id', 'string', 'Deck id (required).'), f('json', 'boolean', 'Output JSON.')], 'ant decks remove --room zj4jlety9q --id abc', 'scripts/ant-cli-decks.mjs:168-188'),
  av('stage-focus', 'stage', 'focus', 'stage focus <deckId> --slide-index N [--slide-id ID] [--plan PLAN_ID] [--json]', 'Publish the current slide of an existing deck into Stage focus. Sends pidChain so agents can use the same authenticated path as browser viewers.', [f('slide-index', 'number', 'Zero-based slide index to publish (required).'), f('slide-id', 'string', 'Optional slide id consistency check.'), f('plan', 'string', 'Optional plan id for the stage_focus evidence event.'), f('json', 'boolean', 'Emit JSON instead of human text.')], 'ant stage focus deck_abc --slide-index 2 --slide-id s3 --plan stage-primitive-v1', 'scripts/ant-cli-stage.mjs:1-118'),
  av('stage-current', 'stage', 'current', 'stage current <deckId> [--json]', 'Read the current focus for an existing deck. Sends pidChain query auth so agents can inspect Stage state without a browser.', [f('json', 'boolean', 'Emit JSON instead of human text.')], 'ant stage current deck_abc', 'scripts/ant-cli-stage.mjs:1-118'),

  // === chat (name-aware + send/reply/pending) — SHIPPED 2026-05-16 ===
  av('chat-send', 'chat', 'send',
    'chat send <roomId> --msg "..." [--handle @h] [--kind K] [--parent-message ID] [--json]',
    'Post a message into a room. Principal verb for sending; `rooms post` is the internal route name. pidChain is appended automatically so the server resolves the caller.',
    [f('room', 'string', 'Room ID (required; first positional accepted).'),
     f('msg', 'string', 'Message body (required; --body alias accepted).'),
     f('handle', 'string', 'Override author handle (default: PID-chain resolved).'),
     f('kind', 'enum', 'Message kind.', { constraint: 'human|agent|system|system-break' }),
     f('parent-message', 'string', 'Reply parent message id.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat send ${ROOM_ID_EX} --msg 'slice ready'`,
    'scripts/ant-cli-chat.mjs:62-64,229-258'),
  av('chat-reply', 'chat', 'reply',
    'chat <chatname> reply <messageId> <message...> [--handle @h] [--json]',
    'Reply to a specific message via the name-aware shape. POSTs with parentMessageId set so the message threads under the parent.',
    [f('handle', 'string', 'Override author handle.'),
     f('kind', 'enum', 'Message kind.', { constraint: 'human|agent|system|system-break' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant chat antDevTeam reply msg_p 'agreed — locking'`,
    'scripts/ant-cli-chat.mjs:101-105,180-204'),
  av('chat-pending', 'chat', 'pending',
    'chat pending --handle @me [--since <epochMs>] [--json]',
    'List messages addressed to the caller that have not been threaded a reply. Wraps GET /api/chat-rooms/messages/pending.',
    [f('handle', 'string', 'Caller handle (required).'),
     f('since', 'number', 'Filter by min epoch-ms.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant chat pending --handle @researchant',
    'scripts/ant-cli-chat-pending.mjs:25-62'),
  av('chat-namechange', 'chat', 'namechange',
    'chat <chatname> namechange <new-name> [--json]',
    'Rename a chat room via the name-aware shape. PATCHes /api/chat-rooms/:roomId/name.',
    [f('new-name', 'string', 'New room name (positional accepted).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant chat antDevTeam namechange antDevTeam-v2',
    'scripts/ant-cli-chat.mjs:106,206-220'),
  av('chat-search', 'chat', 'search',
    'chat <chatname> search <query> [--limit N] [--json]',
    'Search within a single chat room (name-aware shape). Wraps GET /api/chat-rooms/:roomId/search.',
    [f('q', 'string', 'Query string (positional or --q).'),
     f('limit', 'number', 'Max matches.', { default: '50', constraint: '1-200' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant chat antDevTeam search manifest',
    'scripts/ant-cli-chat.mjs:107,113-136'),

  // === status — chasing (SHIPPED 2026-05-16) ===
  av('status-chasing', 'status', 'chasing',
    'status chasing --handle @me [--min-idle-minutes N] [--json]',
    'List threads where the caller spoke last and the room has gone quiet. Wraps GET /api/status/chasing.',
    [f('handle', 'string', 'Caller handle (required).'),
     f('min-idle-minutes', 'number', 'Minimum idle minutes to be considered chasing.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant status chasing --handle @researchant --min-idle-minutes 30',
    'scripts/ant-cli-status-chasing.mjs:26-63'),

  // === interview — send + summary (SHIPPED 2026-05-16) ===
  av('interview-send', 'interview', 'send',
    'interview send <interview-id> --msg "..." [--json]',
    'Send a message into an active interview. POSTs /api/interviews/:id/messages with pidChain.',
    [f('msg', 'string', 'Message body (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant interview send iv_abc123 --msg "follow-up question"',
    'scripts/ant-cli-interview.mjs:72-84'),
  av('interview-summary', 'interview', 'summary',
    'interview summary <interview-id> [--json]',
    'Show the interview summary (status, participants, duration, first/middle/last message). Wraps GET /api/interviews/:id/summary.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant interview summary iv_abc123',
    'scripts/ant-cli-interview.mjs:86-128'),

  // === mcp list (SHIPPED — sibling to mcp grant/revoke) ===
  av('mcp-list', 'mcp', 'list',
    'mcp list --room R [--include-revoked] [--json] [--admin-token T]',
    'List MCP adapter grants for a room (admin-bearer). Token bytes never printed.',
    [f('room', 'string', 'Room id (required).'),
     f('include-revoked', 'boolean', 'Include revoked grants.'),
     f('admin-token', 'string', 'Admin bearer; falls back to $ANT_ADMIN_TOKEN.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant mcp list --room ${ROOM_ID_EX}`,
    'scripts/ant-cli-mcp.mjs:14-27,87-98'),

  // === reaction add/remove (already shipped as siblings of reaction list) ===
  av('reaction-add', 'reaction', 'add',
    'reaction add --room ROOM_ID --message MESSAGE_ID --handle @h --emoji EMOJI [--json]',
    'Add a canonical-emoji reaction to a message.',
    [f('room', 'string', 'Room ID (required).'),
     f('message', 'string', 'Message ID (required).'),
     f('handle', 'string', 'Reactor handle (required).'),
     f('emoji', 'string', 'Canonical reaction emoji (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant reaction add --room ${ROOM_ID_EX} --message msg_123 --handle @researchant --emoji 👍`,
    'scripts/ant-cli-reaction.mjs:8,68-78'),
  av('reaction-remove', 'reaction', 'remove',
    'reaction remove --room ROOM_ID --message MESSAGE_ID --handle @h --emoji EMOJI [--json]',
    'Remove a reaction from a message.',
    [f('room', 'string', 'Room ID (required).'),
     f('message', 'string', 'Message ID (required).'),
     f('handle', 'string', 'Reactor handle (required).'),
     f('emoji', 'string', 'Canonical reaction emoji (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    `ant reaction remove --room ${ROOM_ID_EX} --message msg_123 --handle @researchant --emoji 👍`,
    'scripts/ant-cli-reaction.mjs:9,80-89'),

  // === sessions — create + export (SHIPPED 2026-05-16) ===
  av('sessions-create', 'sessions', 'create',
    'sessions create <name> [--agent-kind KIND] [--cwd PATH] [--handle @x] [--json]',
    'Alias of `ant new terminal`. POSTs /api/terminals to spawn a fresh terminal + terminal chat + tmux pane. Preserves v3 muscle-memory.',
    [f('name', 'string', 'Terminal name (required; positional accepted).'),
     f('agent-kind', 'enum', 'Agent kind.', { constraint: 'claude|codex|pi|gemini|qwen|copilot' }),
     f('cwd', 'string', 'Initial working directory.'),
     f('handle', 'string', 'Override caller handle.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant sessions create research-overnight --agent-kind claude',
    'scripts/ant-cli-sessions.mjs:30-55,90-118'),
  av('sessions-export', 'sessions', 'export',
    'sessions export <session-or-room-id> [--format markdown|json|text] [--out FILE] [--json]',
    'Download a full server-side session/room export. Uses GET /api/sessions/:id/export so lazy-loaded chat pages do not truncate exports.',
    [f('room', 'string', 'Session id or room id (positional accepted).'),
     f('format', 'enum', 'Export format.', { constraint: 'markdown|json|text' }),
     f('out', 'string', 'Output file; omit to print to stdout.'),
     f('json', 'boolean', 'Shortcut for --format json; emits JSON summary when used with --out.')],
    'ant sessions export antDevTeam --format markdown --out /tmp/antDevTeam.md',
    'scripts/ant-cli-sessions.mjs:30-55,117-147; src/routes/api/sessions/[id]/export/+server.ts'),

  // === new — terminal + chat/chatroom (SHIPPED 2026-05-16, JWPK verb spec) ===
  av('new-terminal', 'new', 'terminal',
    'new terminal <name> [--agent-kind KIND] [--cwd PATH] [--handle @x] [--json]',
    'Spawn a fresh terminal + terminal chat + tmux pane. POSTs /api/terminals with auto-register-at-spawn so terminal chat self-post works from inside the spawned shell.',
    [f('name', 'string', 'Terminal name (required; positional accepted).'),
     f('agent-kind', 'enum', 'Agent kind.', { constraint: 'claude|codex|pi|gemini|qwen|copilot' }),
     f('cwd', 'string', 'Initial working directory.'),
     f('handle', 'string', 'Override caller handle.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant new terminal worker-2 --agent-kind codex',
    'scripts/ant-cli-new.mjs:21-45,78-106'),
  av('new-chat', 'new', 'chat',
    'new chat <name> [--json]   (alias: new chatroom)',
    'Create a new chat room. POSTs /api/chat-rooms with { name }. `chatroom` is an accepted alias.',
    [f('name', 'string', 'Chat room name (required; positional accepted).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant new chat planning-room',
    'scripts/ant-cli-new.mjs:21-45,108-122'),

  // === list — terminals + chatrooms (SHIPPED 2026-05-16) ===
  av('list-terminals', 'list', 'terminals',
    'list terminals [--json]',
    'List every terminal (one line each: sessionId, name, agentKind, derivedHandle, alive/stopped). Wraps GET /api/terminals.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant list terminals',
    'scripts/ant-cli-list.mjs:14-30,59-78'),
  av('list-chatrooms', 'list', 'chatrooms',
    'list chatrooms [--json]   (alias: list chats)',
    'List every chat room (one line each: id, name, attentionState). Wraps GET /api/chat-rooms. Terminal chats are intentionally hidden — use `list terminals` for those.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant list chatrooms',
    'scripts/ant-cli-list.mjs:14-30,80-98'),

  // === terminal — name-aware sub-verbs (SHIPPED 2026-05-16, JWPK verb spec) ===
  av('terminal-name', 'terminal', 'name',
    'terminal name   (alias: terminal handle)',
    'Show the terminal handle for the current pid via PID-chain → /api/identity/resolve. `handle` is an accepted alias.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal name',
    'scripts/ant-cli-terminal.mjs:48-65,133-159'),
  av('terminal-namechange', 'terminal', 'namechange',
    'terminal <name> namechange <new-name> [--json]',
    'Rename a terminal. PATCHes /api/terminals/:sessionId with { name: <new> }.',
    [f('new-name', 'string', 'New terminal name (positional accepted).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 namechange worker-2-archived',
    'scripts/ant-cli-terminal.mjs:76,179-192'),
  av('terminal-post', 'terminal', 'post',
    'terminal <name> post <msg...> [--json]',
    "Post a message into the terminal chat. pidChain is appended automatically.",
    [f('msg', 'string', 'Message body (positional accepted).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 post "slice ready for review"',
    'scripts/ant-cli-terminal.mjs:77,194-216'),
  av('terminal-localtmux', 'terminal', 'localtmux',
    'terminal <name> localtmux [--json]',
    'Print the local `tmux attach-session -t <sessionId>` command for the named terminal (pipe to pbcopy / xclip).',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 localtmux',
    'scripts/ant-cli-terminal.mjs:78,218-228'),
  av('terminal-sshtmux', 'terminal', 'sshtmux',
    'terminal <name> sshtmux [--host HOST] [--json]',
    'Print the ssh-based tmux attach command (host from $ANT_SSH_HOST env; operator must set it).',
    [f('host', 'string', 'SSH host override.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 sshtmux --host mac.local',
    'scripts/ant-cli-terminal.mjs:79,230-241'),
  av('terminal-whatcli', 'terminal', 'whatcli',
    'terminal <name> whatcli [--json]',
    'Show the agent_kind for the named terminal (claude / codex / pi / gemini / qwen / copilot).',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 whatcli',
    'scripts/ant-cli-terminal.mjs:80,243-252'),
  av('terminal-setcli', 'terminal', 'setcli',
    'terminal <name> setcli <kind> [--json]',
    'Set the agent_kind for the named terminal. PATCHes /api/terminals/:sessionId with { agentKind }.',
    [f('kind', 'enum', 'Agent kind.', { constraint: 'claude|codex|pi|gemini|qwen|copilot' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 setcli codex',
    'scripts/ant-cli-terminal.mjs:81,254-270'),
  av('terminal-search', 'terminal', 'search',
    'terminal <name> search <query> [--limit N] [--json]',
    "Search messages inside the terminal chat. Wraps GET /api/chat-rooms/:linkedChatRoomId/search.",
    [f('q', 'string', 'Query string (positional or --q).'),
     f('limit', 'number', 'Max matches.', { default: '50', constraint: '1-200' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 search "TODO"',
    'scripts/ant-cli-terminal.mjs:82,272-300'),
  av('terminal-listchatrooms', 'terminal', 'listchatrooms',
    'terminal <name> listchatrooms [--json]',
    'List every chat room the named terminal is a member of (one line each: id, name, role). Wraps GET /api/terminals/:sessionId/chatrooms.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 listchatrooms',
    'scripts/ant-cli-terminal.mjs:83,302-316'),
  av('terminal-listfiles', 'terminal', 'listfiles',
    'terminal <name> listfiles [--json]',
    'List every flagged file scoped to the named terminal. Wraps GET /api/terminals/:sessionId/files.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 listfiles',
    'scripts/ant-cli-terminal.mjs:84,318-337'),
  av('terminal-listtasks', 'terminal', 'listtasks',
    'terminal <name> listtasks [--json]',
    'List every task scoped to the named terminal. Wraps GET /api/terminals/:sessionId/tasks.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 listtasks',
    'scripts/ant-cli-terminal.mjs:85,339-358'),
  av('terminal-listmemories', 'terminal', 'listmemories',
    'terminal <name> listmemories [--json]',
    'List every scope=terminal memory row for the named terminal. Wraps GET /api/terminals/:sessionId/memories.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 listmemories',
    'scripts/ant-cli-terminal.mjs:86,360-376'),
  av('terminal-read', 'terminal', 'read',
    'terminal <name> read [--lines N] [--json]',
    'Print raw terminal scrollback (all run-event kinds — includes raw-trust "guff"). Wraps GET /api/terminals/:sessionId/run-events?limit=N.',
    [f('lines', 'number', 'Lines to fetch.', { default: '100', constraint: '1-1000' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 read --lines 200',
    'scripts/ant-cli-terminal.mjs:87,385-413'),
  av('terminal-antread', 'terminal', 'antread',
    'terminal <name> antread [--lines N] [--json]',
    'Print ANT-cleaned terminal scrollback (skips raw-trust "guff" — only message/tool_call/command/thinking/agent_prompt).',
    [f('lines', 'number', 'Lines to fetch.', { default: '100', constraint: '1-1000' }),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant terminal worker-2 antread --lines 200',
    'scripts/ant-cli-terminal.mjs:88,385-413'),
  av('terminal-history', 'terminal', 'history',
    'terminal <name> history [--since 5m|1h] [--grep text] [--limit N] [--raw] [--json]',
    'Terminal history query with relative time, text search, and raw ANSI support. #112 v3-parity.',
    [f('since', 'string', 'Relative time (5m, 1h, 30s, 1d) or timestamp/ms.'),
     f('grep', 'string', 'Text search query.'),
     f('limit', 'number', 'Max events.', { default: '100' }),
     f('raw', 'boolean', 'Include raw ANSI bytes.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant terminal worker-2 history --since 1h --grep error',
    'scripts/ant-cli-terminal.mjs:87,388-439'),

  // === settings — scope-aware shortcuts (SHIPPED 2026-05-16) ===
  av('settings-addterminalshortcut', 'settings', 'addterminalshortcut',
    'settings addterminalshortcut --terminal NAME --label LBL --command CMD [--json]',
    'Add a terminal-scoped shortcut (resolves terminal name client-side via the shared resolver, POSTs /api/shortcuts).',
    [f('terminal', 'string', 'Terminal name / id / handle (required).'),
     f('label', 'string', 'Shortcut label (required).'),
     f('command', 'string', 'Shortcut command body (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant settings addterminalshortcut --terminal worker-2 --label tests --command "bun run code-qa"',
    'scripts/ant-cli-settings.mjs:29-30,124-139'),
  av('settings-addchatroomshortcut', 'settings', 'addchatroomshortcut',
    'settings addchatroomshortcut --chat NAME --label LBL --command CMD [--json]',
    'Add a chatroom-scoped shortcut. Resolves chat name client-side, POSTs /api/shortcuts.',
    [f('chat', 'string', 'Chat room name / id (required).'),
     f('label', 'string', 'Shortcut label (required).'),
     f('command', 'string', 'Shortcut command body (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant settings addchatroomshortcut --chat antDevTeam --label ping --command "ping all"',
    'scripts/ant-cli-settings.mjs:31-32,141-156'),
  av('settings-listshortcuts', 'settings', 'listshortcuts',
    'settings listshortcuts [--terminal NAME | --chat NAME] [--json]',
    'List shortcuts. With no flag returns global bucket; --terminal / --chat narrows to that scope (exactly one allowed).',
    [f('terminal', 'string', 'Filter to a terminal scope.'),
     f('chat', 'string', 'Filter to a chatroom scope.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant settings listshortcuts --terminal worker-2',
    'scripts/ant-cli-settings.mjs:33-34,158-197'),
  av('settings-removeshortcut', 'settings', 'removeshortcut',
    'settings removeshortcut <id> [--json]',
    'Remove a shortcut by id. DELETEs /api/shortcuts/:id.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant settings removeshortcut sc_abc123',
    'scripts/ant-cli-settings.mjs:35-36,199-206'),

  // === task — JWPK TASKS-SUBSYSTEM (SHIPPED 2026-05-16) ===
  av('task-list', 'task', 'list',
    'task list [--terminal NAME] [--status S] [--assigned @h] [--room NAME] [--json]',
    'List tasks; filterable by terminal / status / assignee / room. Wraps GET /api/tasks with name → id resolution client-side.',
    [f('terminal', 'string', 'Filter by terminal (name / id / handle).'),
     f('status', 'enum', 'Filter by status.', { constraint: 'todo|in_progress|done|cancelled|blocked' }),
     f('assigned', 'string', 'Filter by assignee handle.'),
     f('room', 'string', 'Filter by room (name / id).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant task list --status todo',
    'scripts/ant-cli-task.mjs:25-41,81-138'),
  av('task-create', 'task', 'create',
    'task create --title TEXT [--description TEXT] [--terminal NAME] [--assigned @h] [--room NAME] [--plan PLAN_ID] [--json]',
    'Create a task. POSTs /api/tasks with optional terminal / room scoping and plan binding.',
    [f('title', 'string', 'Task title (required).'),
     f('description', 'string', 'Task description.'),
     f('terminal', 'string', 'Bind task to this terminal.'),
     f('assigned', 'string', 'Initial assignee handle.'),
     f('room', 'string', 'Bind task to this room.'),
     f('plan', 'string', 'Attach task to this plan id so it appears in the plan overview.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant task create --title "ship manifest polish" --assigned @researchant --plan v4-fresh-ant',
    'scripts/ant-cli-task.mjs:25-41,140-169'),
  av('task-done', 'task', 'done',
    'task done <taskId> [--json]',
    'Mark a task done. PATCHes /api/tasks/:taskId with { status: "done" }.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant task done t_abc123',
    'scripts/ant-cli-task.mjs:25-41,171-188'),
  av('task-assign', 'task', 'assign',
    'task assign <taskId> --to @handle [--json]',
    'Assign a task to a handle. PATCHes /api/tasks/:taskId with { assigned_to }.',
    [f('to', 'string', 'Assignee handle (required).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant task assign t_abc123 --to @claude2',
    'scripts/ant-cli-task.mjs:25-41,190-210'),

  // === memory — CRUD + audit (SHIPPED 2026-05-16) ===
  av('memory-get', 'memory', 'get',
    'memory get <key> [--json]',
    'Fetch one memory row by key. Wraps GET /api/memories/key/<key>. Exits 1 with friendly text on 404.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant memory get team/standup-time',
    'scripts/ant-cli-memory.mjs:68-90,203-217'),
  av('memory-put', 'memory', 'put',
    'memory put <key> --value TEXT [--scope global|terminal|room] [--target TARGET] [--by HANDLE] [--json]',
    'Upsert a memory row. POSTs /api/memories with key/value/scope/scope_target/byHandle.',
    [f('value', 'string', 'Memory value (required).'),
     f('scope', 'enum', 'Scope.', { default: 'global', constraint: 'global|terminal|room' }),
     f('target', 'string', 'Scope target id (terminal/room when scope != global).'),
     f('by', 'string', 'Author handle for audit.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant memory put team/standup-time --value "09:30 BST"',
    'scripts/ant-cli-memory.mjs:92-118,203-217'),
  av('memory-list', 'memory', 'list',
    'memory list [--prefix P | --terminal NAME | --room NAME] [--json]',
    'List memories. With no flag returns globals; --prefix narrows by key prefix; --terminal / --room narrows by scope. Exactly one filter.',
    [f('prefix', 'string', 'Filter by key prefix.'),
     f('terminal', 'string', 'Filter to terminal scope (name / id / handle).'),
     f('room', 'string', 'Filter to room scope (name / id).'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant memory list --terminal worker-2',
    'scripts/ant-cli-memory.mjs:120-157,203-217'),
  av('memory-delete', 'memory', 'delete',
    'memory delete <key> [--by HANDLE] [--json]',
    'Delete a memory row. DELETEs /api/memories/key/<key>. Exits 1 with friendly text on 404.',
    [f('by', 'string', 'Author handle for audit.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant memory delete team/standup-time --by @researchant',
    'scripts/ant-cli-memory.mjs:159-181,203-217'),
  av('memory-audit', 'memory', 'audit',
    'memory audit [--key K] [--limit N] [--json]',
    'Show memory audit trail. Wraps GET /api/memories/audit.',
    [f('key', 'string', 'Filter audit log to this key.'),
     f('limit', 'number', 'Max rows.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant memory audit --limit 50',
    'scripts/ant-cli-memory.mjs:183-201,203-217'),

  // === flag — file-refs subsystem (SHIPPED 2026-05-16) ===
  av('flag-add', 'flag', 'add',
    'flag add <file_path> [--terminal NAME | --chat NAME] [--label TEXT] [--description TEXT] [--json]',
    'Flag a file into global / terminal / chatroom scope. POSTs /api/file-refs with names resolved client-side.',
    [f('terminal', 'string', 'Bind file-ref to a terminal scope.'),
     f('chat', 'string', 'Bind file-ref to a chatroom scope.'),
     f('label', 'string', 'Short label.'),
     f('description', 'string', 'Long description.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant flag add docs/onboarding.md --label onboarding',
    'scripts/ant-cli-flag.mjs:83-105,158-171'),
  av('flag-list', 'flag', 'list',
    'flag list [--terminal NAME | --chat NAME | --path PATH] [--json]',
    'List file-refs. No flag = global scope; --terminal / --chat narrows to scope; --path narrows to a single file path. Exactly one filter.',
    [f('terminal', 'string', 'Filter to a terminal scope.'),
     f('chat', 'string', 'Filter to a chatroom scope.'),
     f('path', 'string', 'Filter to a single file path.'),
     f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant flag list --terminal worker-2',
    'scripts/ant-cli-flag.mjs:107-142,158-171'),
  av('flag-remove', 'flag', 'remove',
    'flag remove <id> [--json]',
    'Remove a file-ref by id. DELETEs /api/file-refs/:id.',
    [f('json', 'boolean', 'Emit JSON instead of human text.')],
    'ant flag remove fr_abc123',
    'scripts/ant-cli-flag.mjs:144-156,158-171'),

  // planned (manual-sourced) — verbs named verbatim in the fresh-ANT
  // manual (2026-05-13) as customer-facing promises; CLI wrapper to ship.
  // source_ref = MANUAL distinguishes these from DP-sourced planned verbs.
  av('chat-focus', 'chat', 'focus',
    'chat focus <roomId> --member @h [--for 30m|1h|2d] [--reason "..."] [--json]',
    'Flag a member as head-down / do-not-interrupt in a room. `--for` sets an auto-clear timer (default indefinite); `--reason` adds a short note. Wraps PUT /api/chat-rooms/:roomId/focus-mode.',
    [
      f('member', 'string', 'Member handle to focus.', { default: '@you' }),
      f('for', 'string', 'Auto-clear duration (e.g. 30m, 1h, 2d).'),
      f('reason', 'string', 'Short reason.'),
      f('json', 'boolean', 'Emit JSON.')
    ],
    `ant chat focus ${ROOM_ID_EX} --member @you --for 30m --reason "writing PR"`,
    `${CHAT}:runFocus`),
  av('chat-unfocus', 'chat', 'unfocus',
    'chat unfocus <roomId> --member @h [--json]',
    'Clear the head-down signal in a room. Wraps DELETE /api/chat-rooms/:roomId/focus-mode.',
    [f('member', 'string', 'Member handle to unfocus.', { default: '@you' }), f('json', 'boolean', 'Emit JSON.')],
    `ant chat unfocus ${ROOM_ID_EX} --member @you`,
    `${CHAT}:runUnfocus`),
  av('chat-decide', 'chat', 'decide',
    'chat decide <roomId> <discussionId> <decision-text...> [--json]',
    'Close a discussion thread with a recorded decision. The decision becomes the summary; status flips to closed. Wraps PATCH /api/chat-rooms/:roomId/discussions/:discussionId.',
    [f('json', 'boolean', 'Emit JSON.')],
    `ant chat decide ${ROOM_ID_EX} disc_abc use postgres`,
    `${CHAT}:runDecide;src/routes/api/chat-rooms/[roomId]/discussions/[discussionId]/+server.ts:1-60`),
  av('plan-list', 'plan', 'list',
    'plan list [--include-archived] [--json]',
    'List every plan (archived hidden by default).',
    [f('include-archived', 'boolean', 'Include archived plans.'), f('json', 'boolean', 'Emit JSON.')],
    'ant plan list',
    `${PLAN}:runListPlansVerb`),
  av('plan-archive', 'plan', 'archive',
    'plan archive <planId> [--unarchive] [--json]',
    'Archive (or with --unarchive, restore) a whole plan. Reads ANT_ADMIN_BEARER from env. Wraps PATCH /api/plans/:planId with `{ action: "archive"|"unarchive" }`.',
    [f('unarchive', 'boolean', 'Unarchive instead of archive.'), f('json', 'boolean', 'Emit JSON.')],
    `ant plan archive ${PLAN_ID_EX}`,
    `${PLAN}:runArchivePlanVerb`),
  av('plan-cron-list', 'plan', 'cron',
    'plan cron list [--include-deleted] [--json]',
    'List recurring plan jobs. Wraps GET /api/cron-jobs.',
    [f('include-deleted', 'boolean', 'Include soft-deleted cron jobs.'), f('json', 'boolean', 'Emit JSON.')],
    'ant plan cron list',
    'scripts/ant-cli-plan-cron.mjs:runList;src/routes/api/cron-jobs/+server.ts:1-40'),
  av('plan-cron-create', 'plan', 'cron',
    'plan cron create --name NAME --every-minutes N [--room ROOM_ID] [--message TEXT] [--start] [--json]',
    'Create a named recurring job. Room/message jobs post into a room; otherwise the default action is console.log. Wraps POST /api/cron-jobs.',
    [f('name', 'string', 'Job display name.'),
     f('every-minutes', 'number', 'Interval in minutes.'),
     f('interval-ms', 'number', 'Raw interval in milliseconds, alternative to --every-minutes.'),
     f('room', 'string', 'Target room id for room.message jobs.'),
     f('message', 'string', 'Message template for room.message jobs.'),
     f('action', 'string', 'Action: room.message, console.log, webhook.post, or task.create.'),
     f('created-by', 'string', 'Audit handle for created_by_handle.'),
     f('start', 'boolean', 'Start immediately after creation.'),
     f('json', 'boolean', 'Emit JSON.')],
    `ant plan cron create --name goal-loop --every-minutes 10 --room ${ROOM_ID_EX} --message "/loop progress development to /goal 100%" --start`,
    'scripts/ant-cli-plan-cron.mjs:runCreate;src/routes/api/cron-jobs/+server.ts:42-84'),
  av('plan-cron-show', 'plan', 'cron',
    'plan cron show <jobId> [--json]',
    'Show one recurring plan job. Wraps GET /api/cron-jobs/:jobId.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant plan cron show cron_123',
    'scripts/ant-cli-plan-cron.mjs:runShow;src/routes/api/cron-jobs/[jobId]/+server.ts:1-34'),
  av('plan-cron-lifecycle', 'plan', 'cron',
    'plan cron start|pause|stop|delete <jobId> [--json]',
    'Control a recurring plan job lifecycle. Delete is a soft-delete for audit. Wraps PATCH /api/cron-jobs/:jobId.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant plan cron pause cron_123',
    'scripts/ant-cli-plan-cron.mjs:runLifecycle;src/routes/api/cron-jobs/[jobId]/+server.ts:36-87'),
  av('tunnel-list', 'tunnel', 'list',
    'tunnel list --room ROOM_ID [--json]',
    'List tunnels visible to a room. Wraps GET /api/tunnels?roomId=.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant tunnel list --room zj4jlety9q',
    'scripts/ant-cli-tunnel.mjs:runList'),
  av('tunnel-add', 'tunnel', 'add',
    'tunnel add <slug> --public URL [--local URL] [--title TEXT] [--rooms room-id,...] [--access-required] [--json]',
    'Register a public URL as a tunnel scoped to the caller room. Wraps POST /api/tunnels.',
    [f('public', 'string', 'Public URL (e.g. Cloudflare Tunnel).'),
     f('local', 'string', 'Local dev URL (e.g. http://localhost:5173).'),
     f('title', 'string', 'Optional display title.'),
     f('rooms', 'string', 'Comma-separated room ids allowed to view.'),
     f('access-required', 'boolean', 'Cloudflare Access gating.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant tunnel add prototype --public https://proto.trycloudflare.com',
    'scripts/ant-cli-tunnel.mjs:runAdd'),
  av('tunnel-status', 'tunnel', 'status',
    'tunnel status <slug> [--json]',
    'Show details for one tunnel. Wraps GET /api/tunnels/:slug.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant tunnel status prototype',
    'scripts/ant-cli-tunnel.mjs:runShow'),
  av('tunnel-remove', 'tunnel', 'remove',
    'tunnel remove <slug> [--json]',
    'Delete a tunnel. Wraps DELETE /api/tunnels/:slug.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant tunnel remove prototype',
    'scripts/ant-cli-tunnel.mjs:runRemove'),
  av('pairing-generate', 'pairing', 'generate',
    'pairing generate --room ROOM_ID [--expires-hours 24] [--json]',
    'Generate a QR pairing token for device onboarding. Wraps POST /api/pairing-tokens.',
    [f('room', 'string', 'Room ID to bind the token to.'),
     f('expires-hours', 'number', 'Token lifetime in hours (default 24).'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant pairing generate --room zj4jlety9q',
    'scripts/ant-cli-pairing.mjs:generateToken'),
  av('pairing-consume', 'pairing', 'consume',
    'pairing consume <token> [--device-name NAME] [--json]',
    'Consume a pairing token to register a device. Wraps POST /api/pairing-tokens/:token.',
    [f('device-name', 'string', 'Device name for audit.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant pairing consume abc123 --device-name iPad',
    'scripts/ant-cli-pairing.mjs:consumeToken'),
  av('pairing-list', 'pairing', 'list',
    'pairing list --room ROOM_ID [--json]',
    'List pairing tokens for a room. Wraps GET /api/pairing-tokens?roomId=.',
    [f('room', 'string', 'Room ID.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant pairing list --room zj4jlety9q',
    'scripts/ant-cli-pairing.mjs:listTokens'),
  av('pairing-revoke', 'pairing', 'revoke',
    'pairing revoke <token> [--json]',
    'Revoke a pairing token. Wraps DELETE /api/pairing-tokens/:token.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant pairing revoke abc123',
    'scripts/ant-cli-pairing.mjs:revokeToken'),
  av('pairing-qr', 'pairing', 'qr',
    'pairing qr <token> [--json]',
    'Show QR code URL for a pairing token.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant pairing qr abc123',
    'scripts/ant-cli-pairing.mjs:showQr'),
  av('share-create', 'share', 'create',
    'share create --room ROOM_ID [--title TEXT] [--scope room|messages|tasks|plan] [--expires-hours N] [--json]',
    'Create a read-only public share link for a room. Wraps POST /api/share.',
    [f('room', 'string', 'Room ID.'),
     f('title', 'string', 'Optional display title.'),
     f('scope', 'enum', 'Shared content scope.', { constraint: 'room|messages|tasks|plan' }),
     f('expires-hours', 'number', 'Link lifetime in hours.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant share create --room zj4jlety9q --scope messages',
    'scripts/ant-cli-share.mjs:createShare'),
  av('share-list', 'share', 'list',
    'share list --room ROOM_ID [--json]',
    'List share links for a room. Wraps GET /api/share?roomId=.',
    [f('room', 'string', 'Room ID.'),
     f('json', 'boolean', 'Emit JSON.')],
    'ant share list --room zj4jlety9q',
    'scripts/ant-cli-share.mjs:listShares'),
  av('share-revoke', 'share', 'revoke',
    'share revoke <token> [--json]',
    'Revoke a share link. Wraps DELETE /api/share/:token.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant share revoke abc123',
    'scripts/ant-cli-share.mjs:revokeShare'),
    av('agents-list', 'agents', 'list',
    'agents list [--room ROOM_ID] [--json]',
    'List agents globally or in one room. Wraps GET /api/agents.',
    [f('room', 'string', 'Room ID to filter.'), f('json', 'boolean', 'Emit JSON.')],
    'ant agents list --room zj4jlety9q',
    'scripts/ant-cli-agents.mjs:runList'),
  av('agents-show', 'agents', 'show',
    'agents show <handle> [--json]',
    'Show one agent with room memberships. Wraps GET /api/agents/:handle.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant agents show @evolveantcodex',
    'scripts/ant-cli-agents.mjs:runShow'),
  av('agents-set', 'agents', 'set',
    'agents set <handle> --color HEX --icon EMOJI --bg-style card|tint|transparent [--json]',
    'Update agent metadata globally. Wraps PATCH /api/agents/:handle.',
    [f('color', 'string', 'Display color hex.'), f('icon', 'string', 'Display icon/emoji.'), f('bg-style', 'string', 'Background style: card, tint, transparent.'), f('name', 'string', 'Display name override.'), f('json', 'boolean', 'Emit JSON.')],
    'ant agents set @evolveantcodex --color #ff0000 --icon 🤖',
    'scripts/ant-cli-agents.mjs:runSet'),
av('share-show', 'share', 'show',
    'share show <token> [--json]',
    'Show shared content for a token. Wraps GET /api/share/:token.',
    [f('json', 'boolean', 'Emit JSON.')],
    'ant share show abc123',
    'scripts/ant-cli-share.mjs:showShare')

];

export const listAvailableVerbs = () => manifestData.filter((v) => v.status === 'available');
export const listNeedsWrapperVerbs = () => manifestData.filter((v) => v.status === 'needs-wrapper');
export const listPlannedVerbs = () => manifestData.filter((v) => v.status === 'planned');
export const findVerbById = (id: string) => manifestData.find((v) => v.id === id);
