import { execFileSync } from 'child_process';
import { homedir } from 'os';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
} from 'fs';
import { createHash } from 'crypto';

const MODULE_DIR = dirname(fileURLToPath(import.meta.url));

// Per-CLI hook target. The dir is created on real install; templates are
// copied verbatim from docs/agent-setup/hooks/<cli>/.
//
// The state-emitting hook scripts themselves are generated by pasting
// the bootstrap-prompt.md into the target CLI — this command stages the
// reference templates so the user (or a CLI agent) can finish the wire-
// up. See docs/agent-setup/hooks/<cli>/bootstrap-prompt.md for the rest.
export type AgentCli =
  | 'claude-code'
  | 'codex-cli'
  | 'gemini-cli'
  | 'qwen-cli'
  | 'copilot-cli'
  | 'pi';

const TARGET_DIR_BY_CLI: Record<AgentCli, string> = {
  'claude-code': '.claude/hooks/ant-status',
  'codex-cli': '.codex/hooks/ant-status',
  'gemini-cli': '.gemini/hooks/ant-status',
  'qwen-cli': '.qwen/hooks/ant-status',
  'copilot-cli': '.copilot/hooks/ant-status',
  pi: '.pi/hooks/ant-status',
};

const KNOWN_CLIS = Object.keys(TARGET_DIR_BY_CLI) as AgentCli[];

export type FileAction = 'new' | 'updated' | 'unchanged';

export interface FileResult {
  source: string;
  target: string;
  action: FileAction;
}

export interface InstallResult {
  cli: AgentCli;
  sourceDir: string;
  targetDir: string;
  files: FileResult[];
  dryRun: boolean;
}

function isAgentCli(value: string): value is AgentCli {
  return (KNOWN_CLIS as string[]).includes(value);
}

function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

/**
 * Stage hook templates for one CLI. Pure function over the filesystem
 * so it's exercised directly by the unit test — no spawn, no env
 * inheritance. Idempotent: re-running with no source change leaves
 * every file `unchanged`.
 *
 * Throws if the source dir is missing (caller decides how to surface).
 */
export function installCliHooks(opts: {
  cli: AgentCli;
  repoRoot: string;
  home?: string;
  dryRun?: boolean;
}): InstallResult {
  const home = opts.home ?? process.env.HOME ?? homedir();
  const sourceDir = join(opts.repoRoot, 'docs', 'agent-setup', 'hooks', opts.cli);
  const targetDir = join(home, TARGET_DIR_BY_CLI[opts.cli]);

  if (!existsSync(sourceDir)) {
    throw new Error(`Source templates not found: ${sourceDir}`);
  }

  const entries = readdirSync(sourceDir).filter((name) => {
    const stat = statSync(join(sourceDir, name));
    return stat.isFile();
  });

  const files: FileResult[] = [];
  for (const name of entries) {
    const source = join(sourceDir, name);
    const target = join(targetDir, name);
    const sourceBuf = readFileSync(source);

    let action: FileAction;
    if (existsSync(target)) {
      const targetBuf = readFileSync(target);
      action = sha256(sourceBuf) === sha256(targetBuf) ? 'unchanged' : 'updated';
    } else {
      action = 'new';
    }

    if (!opts.dryRun && action !== 'unchanged') {
      mkdirSync(dirname(target), { recursive: true });
      copyFileSync(source, target);
    }
    files.push({ source, target, action });
  }

  return {
    cli: opts.cli,
    sourceDir,
    targetDir,
    files,
    dryRun: !!opts.dryRun,
  };
}

function printResult(result: InstallResult) {
  const verb = result.dryRun ? 'Would stage' : 'Staged';
  console.log(`${verb} ${result.cli} templates in ${result.targetDir}:`);
  for (const f of result.files) {
    const tag = f.action === 'unchanged' ? '·' : f.action === 'new' ? '+' : '~';
    console.log(`  ${tag} ${f.action.padEnd(9)} ${f.target}`);
  }
  if (!result.dryRun) {
    console.log('');
    console.log(`Next: paste docs/agent-setup/hooks/${result.cli}/bootstrap-prompt.md`);
    console.log(`into ${result.cli} on this host to generate per-event scripts.`);
  }
}

function repoRoot(): string {
  return join(MODULE_DIR, '../..');
}

function legacyShellCaptureInstall() {
  const installScript = join(MODULE_DIR, '../../ant-capture/install.sh');
  if (!existsSync(installScript)) {
    console.error('Install script not found. Make sure ant-capture/ directory exists.');
    process.exit(1);
  }
  execFileSync('bash', [installScript], { stdio: 'inherit' });
}

export async function hooks(args: string[], flags: any = {}) {
  const subcommand = args[0];
  if (subcommand === 'install') {
    const target = args[1];

    // Backward compat: `ant hooks install` (no arg) → legacy zshrc capture.
    if (!target) {
      legacyShellCaptureInstall();
      return;
    }

    if (!isAgentCli(target)) {
      console.error(`Unknown CLI: ${target}. Known: ${KNOWN_CLIS.join(', ')}`);
      process.exit(1);
    }

    const dryRun = !!flags['dry-run'] || !!flags.dryRun;
    try {
      const result = installCliHooks({ cli: target, repoRoot: repoRoot(), dryRun });
      printResult(result);
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    }
    return;
  }

  console.log('Usage:');
  console.log('  ant hooks install              # legacy: install shell capture hooks into ~/.zshrc');
  console.log('  ant hooks install <cli>        # stage hook templates for one CLI');
  console.log(`  Known CLIs: ${KNOWN_CLIS.join(', ')}`);
  console.log('  --dry-run                      # print planned writes only');
}
