#!/usr/bin/env bash
# After a successful "Release ant" GitHub workflow, sync the tap formula
# at Jktfe/homebrew-antchat so `brew install jktfe/antchat/ant` resolves.
#
# Usage:
#   homebrew/update-tap.sh <version>
#   # e.g. homebrew/update-tap.sh 0.1.0
#
# Requirements on the host running this:
#   - GitHub CLI authed: `gh auth status` must pass.
#   - The tap repo `Jktfe/homebrew-antchat` already exists (it ships the
#     antchat formula today — m6.1 T2 just adds Formula/ant.rb alongside).
#
# What it does:
#   1. Downloads SHA256SUMS for the release tag `ant-v<version>`.
#   2. Extracts arm64 + x64 hashes.
#   3. Renders homebrew/ant.rb -> Formula/ant.rb in a fresh tap clone,
#      substituting version + the two PLACEHOLDER hashes.
#   4. Commits on a release/ant-v<version> branch, pushes, opens a tap PR
#      (manual merge keeps a human eye on tap state).
#
# This mirrors homebrew/update-tap.sh in the antchat rail; the only
# differences are the source-formula path, the release-tag prefix, and
# the target filename (Formula/ant.rb vs Formula/antchat.rb).
set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $0 <version>   (e.g. 0.1.0)" >&2
  exit 1
fi

TAG="ant-v${VERSION}"
SOURCE_FORMULA="$(cd "$(dirname "$0")" && pwd)/ant.rb"
RELEASE_REPO="Jktfe/a-nice-terminal"
TAP_REPO="Jktfe/homebrew-antchat"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

cd "$WORKDIR"

echo "==> downloading SHA256SUMS for $TAG"
gh release download "$TAG" --repo "$RELEASE_REPO" --pattern SHA256SUMS

ARM64_SHA="$(awk '/darwin-arm64\.tar\.gz/ {print $1}' SHA256SUMS)"
X64_SHA="$(awk '/darwin-x64\.tar\.gz/ {print $1}' SHA256SUMS)"

if [ -z "$ARM64_SHA" ] || [ -z "$X64_SHA" ]; then
  echo "error: could not extract both hashes from SHA256SUMS" >&2
  cat SHA256SUMS >&2
  exit 1
fi

echo "==> arm64: $ARM64_SHA"
echo "==> x64:   $X64_SHA"

echo "==> cloning tap repo"
gh repo clone "$TAP_REPO" tap
cd tap
git checkout -B "release/$TAG"
mkdir -p Formula

# Render the formula with version + hashes substituted.
sed \
  -e "s/^  version \".*\"/  version \"${VERSION}\"/" \
  -e "s/PLACEHOLDER_ARM64_SHA256_REPLACE_AT_RELEASE_TIME/${ARM64_SHA}/" \
  -e "s/PLACEHOLDER_X64_SHA256_REPLACE_AT_RELEASE_TIME/${X64_SHA}/" \
  "$SOURCE_FORMULA" >Formula/ant.rb

git add Formula/ant.rb
git commit -m "ant ${VERSION}"
git push -u origin "release/$TAG"

gh pr create \
  --repo "$TAP_REPO" \
  --title "ant ${VERSION}" \
  --body "Auto-generated by homebrew/update-tap.sh in jktfe/a-nice-terminal." \
  --head "release/$TAG" \
  --base main

echo "==> tap PR opened. Review + merge to publish."
