#!/usr/bin/env python3
"""
build-audits-index.py — generate ObsidiANT/audits/INDEX.md from frontmatter.

Scans every .md in ObsidiANT/audits/ (except INDEX.md itself), reads YAML
frontmatter title/status/owner/created, and writes a markdown table sorted
by file mtime (newest first).

Run: python3 scripts/build-audits-index.py
Wires: rover-evolveantux task cc35e212.

OBSIDIANT_AUDITS_DIR env var overrides the default if the vault lives
somewhere other than ../ObsidiANT/audits relative to this repo.
"""
import datetime
import os
from pathlib import Path

AUDITS_DIR = Path(os.environ.get(
    'OBSIDIANT_AUDITS_DIR',
    Path(__file__).resolve().parent.parent.parent / 'ObsidiANT' / 'audits'
))
INDEX_PATH = AUDITS_DIR / 'INDEX.md'


def parse_frontmatter(text: str) -> dict:
    if not text.startswith('---\n'):
        return {}
    end = text.find('\n---\n', 4)
    if end == -1:
        return {}
    meta = {}
    for line in text[4:end].split('\n'):
        if ':' in line and not line.strip().startswith('-'):
            k, _, v = line.partition(':')
            meta[k.strip()] = v.strip().strip('"').strip("'")
    return meta


def main() -> None:
    entries = []
    for md in sorted(AUDITS_DIR.glob('*.md')):
        if md.name == 'INDEX.md':
            continue
        text = md.read_text(errors='replace')
        fm = parse_frontmatter(text)
        entries.append({
            'file': md.name,
            'title': fm.get('title') or md.stem,
            'status': fm.get('status', '—'),
            'owner': fm.get('owner', '—').strip('"'),
            'created': fm.get('created', '—'),
            'mtime': datetime.datetime.fromtimestamp(md.stat().st_mtime).strftime('%Y-%m-%d %H:%M'),
        })

    entries.sort(key=lambda e: e['mtime'], reverse=True)

    now = datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%dT%H:%M:%SZ')
    lines = [
        '---',
        'title: Audits — index',
        'type: audit-index',
        f'generated_at: {now}',
        f'count: {len(entries)}',
        '---',
        '',
        '# Audits — index',
        '',
        'Auto-generated by `scripts/build-audits-index.py`. Sorted by file mtime (newest first).',
        '',
        f'**{len(entries)} audit doc(s)**',
        '',
        '| Doc | Status | Owner | Created | Last modified |',
        '|---|---|---|---|---|',
    ]
    for e in entries:
        lines.append(f"| [{e['title']}]({e['file']}) | {e['status']} | {e['owner']} | {e['created']} | {e['mtime']} |")
    lines += ['', '---', '', 'Run `python3 scripts/build-audits-index.py` to regenerate.']
    INDEX_PATH.write_text('\n'.join(lines) + '\n')
    print(f'wrote {INDEX_PATH} with {len(entries)} entries')


if __name__ == '__main__':
    main()
