#!/usr/bin/env bash
# After a successful Release ant workflow, sync the manifest at
# Jktfe/scoop-antchat so `scoop install ant` resolves with the new
# version + hash.
#
# Usage:
#   scoop/update-bucket.sh <version>
#   # e.g. scoop/update-bucket.sh 0.1.0
#
# Requirements on the host running this:
#   - GitHub CLI authed: `gh auth status` must pass
#   - The bucket repo `Jktfe/scoop-antchat` already exists (it ships the
#     antchat manifest today — m6.2 just adds bucket/ant.json alongside).
#
# What it does:
#   1. Downloads SHA256SUMS for the release tag ant-v<version>.
#   2. Extracts the windows-x64 hash.
#   3. Renders scoop/ant.json -> bucket/ant.json in a fresh bucket clone,
#      substituting version (twice — `version` field + URL) and the
#      placeholder hash.
#   4. Commits on a release/ant-v<version> branch, pushes, opens a
#      bucket PR (manual merge keeps a human eye on bucket state).
#
# Mirrors scoop/update-bucket.sh in the antchat rail; the only
# differences are the source-manifest path, the release-tag prefix,
# and the target filename (bucket/ant.json vs bucket/antchat.json).
set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $0 <version>   (e.g. 0.1.0)" >&2
  exit 1
fi

TAG="ant-v${VERSION}"
SOURCE_MANIFEST="$(cd "$(dirname "$0")" && pwd)/ant.json"
RELEASE_REPO="Jktfe/a-nice-terminal"
BUCKET_REPO="Jktfe/scoop-antchat"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

cd "$WORKDIR"

echo "==> downloading SHA256SUMS for $TAG"
gh release download "$TAG" --repo "$RELEASE_REPO" --pattern SHA256SUMS

WIN_X64_SHA="$(awk '/windows-x64\.zip/ {print $1}' SHA256SUMS)"

if [ -z "$WIN_X64_SHA" ]; then
  echo "error: could not extract windows-x64 hash from SHA256SUMS" >&2
  cat SHA256SUMS >&2
  exit 1
fi

echo "==> windows-x64: $WIN_X64_SHA"

echo "==> cloning bucket repo"
gh repo clone "$BUCKET_REPO" bucket-clone
cd bucket-clone
git checkout -B "release/$TAG"
mkdir -p bucket

# Render the manifest with version + hash substituted. The autoupdate
# template uses $version as a literal Scoop placeholder — leave alone.
sed \
  -e "s/\"version\": \"[^\"]*\"/\"version\": \"${VERSION}\"/" \
  -e "s|releases/download/ant-v[0-9][^/]*/ant-[0-9][^-]*-windows-x64\.zip|releases/download/ant-v${VERSION}/ant-${VERSION}-windows-x64.zip|" \
  -e "s/PLACEHOLDER_WIN_X64_SHA256_REPLACE_AT_RELEASE_TIME/${WIN_X64_SHA}/" \
  "$SOURCE_MANIFEST" >bucket/ant.json

git add bucket/ant.json
git commit -m "ant ${VERSION}"
git push -u origin "release/$TAG"

gh pr create \
  --repo "$BUCKET_REPO" \
  --title "ant ${VERSION}" \
  --body "Auto-generated by scoop/update-bucket.sh in jktfe/a-nice-terminal." \
  --head "release/$TAG" \
  --base main

echo "==> bucket PR opened. Review + merge to publish."
