#!/usr/bin/env bash
# After a successful Release antchat workflow, sync the manifest at
# Jktfe/scoop-antchat so `scoop install antchat` resolves with the new
# version + hash.
#
# Usage:
#   scoop/update-bucket.sh <version>
#   # e.g. scoop/update-bucket.sh 1.0.0
#
# Requirements on the host running this:
#   - GitHub CLI authed: `gh auth status` must pass
#   - The bucket repo `Jktfe/scoop-antchat` already exists
#     (one-time bootstrap below)
#
# What it does:
#   1. Downloads SHA256SUMS for the release
#   2. Extracts the windows-x64 hash
#   3. Copies scoop/antchat.json -> bucket/antchat.json in the bucket clone,
#      replaces version (twice — `version` field + URL) and the placeholder
#      hash
#   4. Commits, pushes, opens a bucket PR (manual merge)
#
# Note: Scoop's autoupdate would technically pick up new releases without
# this sync, but updating the bucket on every release keeps `scoop search`
# accurate and gives users a stable manifest to lock against.
#
# One-time bucket bootstrap (run from any host with `gh`):
#   gh repo create Jktfe/scoop-antchat --public \
#     --description "Scoop bucket for antchat (Windows)"
#   git clone https://github.com/Jktfe/scoop-antchat.git
#   cd scoop-antchat && mkdir bucket && touch bucket/.gitkeep
#   git add . && git commit -m "init" && git push origin main

set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $0 <version>   (e.g. 1.0.0)" >&2
  exit 1
fi

TAG="antchat-v${VERSION}"
SOURCE_MANIFEST="$(cd "$(dirname "$0")" && pwd)/antchat.json"
BUCKET_REPO="Jktfe/scoop-antchat"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

cd "$WORKDIR"

echo "==> downloading SHA256SUMS for $TAG"
gh release download "$TAG" --repo Jktfe/a-nice-terminal --pattern SHA256SUMS

WIN_X64_SHA="$(awk '/windows-x64\.zip/ {print $1}' SHA256SUMS)"

if [ -z "$WIN_X64_SHA" ]; then
  echo "error: could not extract windows-x64 hash from SHA256SUMS" >&2
  cat SHA256SUMS >&2
  exit 1
fi

echo "==> windows-x64: $WIN_X64_SHA"

echo "==> cloning bucket repo"
gh repo clone "$BUCKET_REPO" bucket-clone
cd bucket-clone
git checkout -B "release/$TAG"
mkdir -p bucket

# Render the manifest with version + hash substituted. The version
# appears in three spots: the top-level "version" field, the URL, and
# (after substitution at release time) the autoupdate template — but
# autoupdate uses $version as a literal placeholder Scoop expands
# client-side, so leave it alone.
sed \
  -e "s/\"version\": \"[^\"]*\"/\"version\": \"${VERSION}\"/" \
  -e "s|releases/download/antchat-v[0-9][^/]*/antchat-[0-9][^-]*-windows-x64\.zip|releases/download/antchat-v${VERSION}/antchat-${VERSION}-windows-x64.zip|" \
  -e "s/PLACEHOLDER_WIN_X64_SHA256_REPLACE_AT_RELEASE_TIME/${WIN_X64_SHA}/" \
  "$SOURCE_MANIFEST" >bucket/antchat.json

git add bucket/antchat.json
git commit -m "antchat ${VERSION}"
git push -u origin "release/$TAG"

gh pr create \
  --repo "$BUCKET_REPO" \
  --title "antchat ${VERSION}" \
  --body "Auto-generated by scoop/update-bucket.sh in jktfe/a-nice-terminal." \
  --head "release/$TAG" \
  --base main

echo "==> bucket PR opened. Review + merge to publish."
